window.DATOS = {"comerciales":{"AGUSTIN FAVA":{"clientes":{"2001 GRUPO ELECTRO SRL":"C01189","BATTEZZATI JUAN FRANCISCO":"C02315","BRUNO CRUZZOLIN E HIJOS":"C00017","CAC ME SRL":"C01085","CASTELVECCHIO S.A.":"C01355","CASTELVECCHIO S.A. (SAN MIGUEL)":"C01585","CENCOSUD S.A.":"C01956","CRISMANCICH CARLOS A Y SANCHEZ VICTOR H SOC HECHO":"C01505","DISTRIBUCION VANLUZ SRL":"C01155","DISTRIBUIDORA ARGENTINA MATERIALES ELECTRICOS S.R.L.":"C02275","DISTRIBUIDORA S.M. SRL":"C01138","ELECSION S.R.L.":"C01560","ELECTRICIDAD ESCOBAR SRL":"C00536","ELECTRO CASA SERGIO SRL":"C01342","ELECTRO DEL VISO":"C00808","ELECTRO LH":"C00993","ELECTRO MAYO SA":"C02398","ELECTRO PELBA S.A.":"C00310","ELECTRO PLAZA DM S.R.L":"C00667","ELECTRO SCOLLO SRL":"C00515","ELECTRO ZAFIRO SRL":"C01225","ELECTROBAIGOT S.A.":"C02228","ELECTROCESAR S.A.":"C02016","ELECTROWELT S.R.L":"C02784","FERNANDO BERALDO":"C00910","FLORENTIN AVALOS RAFAEL ALCIDES":"C01520","GR ELECTRO E ILUMINACION S.R.L.":"C02139","GRUPO 2SML":"C02833","HVA GLOBAL ELECTRO S.R.L.":"C01190","INMATEL S.A.":"C01444","ISSA PELBA SA":"C00752","JOSE GARCIA VALENCIA":"C00095","JUMALED SA":"C00824","LA ELECTRICA DE LA REJA SRL":"C01337","LICROPANI LUCAS":"C01336","MAYORISTA ELECTRICO LOS GEMELOS S.R.L.":"C01384","MILNE SERGIO GUSTAVO":"C01183","NIGUT ELECTRICIDAD S.A.":"C01167","NISAMAT GROUP S.A":"C00669","NORTHELEC SAS":"C01109","PEREZ NESTOR MIGUEL":"C01100","PONTECORVO RICARDO JAVIER":"C00058","PRIETO MARCELO ANDRES":"C01054","PRIMARC S.A":"C00440","RODRIGUEZ DARIO ANDRES":"C00563","SCHILD FERNANDO GERMAN":"C02581","SCOLLO MATEO":"C02263","SOLUCIONES TECNICAS GENERALES S.R.L.":"C01565","TECNOBROS  S. R. L.":"C01825"}},"AGUSTIN GIAMPIERI":{"clientes":{"ABELCAR S A":"C01674","AGRO BELGRANO S.R.L.":"C02000","ALCIDES JORDAN SORICHETTI E HIJO S.R.L.":"C01405","AR-FI VM S.A.":"C02163","ARGELEC SA":"C01164","CONECTAR SRL":"C01451","CONSTRULUZ S A":"C01904","CONTRULED S. A. S.":"C02326","DEGRA ARGENTINA":"C00475","DIEM RENE":"C01532","DYGELEC SRL":"C01377","EDISON SRL":"C00450","EJF ELECTRICIDAD S.R.L.":"C01659","ELECTRO SOLUCIONES SOCIEDAD POR ACCIONES SIMPLIFICADA":"C01649","EMUN S.A.S.":"C02527","FAICAR S.A.S.":"C02230","FERRERO ALFREDO E HIJOS S.R.L.":"C01450","FUSION GROUP S.A.S.":"C02794","GONZALEZ FRANCISCO MARIANO":"C02195","GONZALEZ SERGIO ARIEL":"C01541","GRUPO CUMBRE S.R.L.":"C01806","JIELI ARGENTINA S.A.":"C01468","JOSE PAPA E HIJOS S A":"C01410","LIGHT CENTRO DE ILUMINACION SR":"C00354","LUMICOR S.A.S.":"C01369","LUMINOTECNIA ARGENTINA S.R.L.":"C00544","MAESTRE ILUMINACION S.A.":"C00446","MARENE S.A.S.":"C02248","MARTINEZ LUCAS ROBERTO":"C00822","PEUSSO SOCIEDAD ANONIMA":"C01700","RICHETTA Y CIA. S.A.":"C00185","RUARTE LUIS MAGIN":"C02205","SAXUM S A":"C02174","SEKIUR S.A.S.":"C02596","STEF S.A.S.":"C01546","TELECTRA S.A.C.I.":"C00367","TOMASELLO AYLEN YAZMIN":"C01406","TOMASELLO MATIAS AGUSTIN":"C01441","WALTER M. BERNARDI":"C01367"}},"ALEJANDRO GIAMPIERI":{"clientes":{"AS SERVICIOS ELECTRICOS":"C01365","BAQUIANO PRODUCTOS Y SERVICIOS SOCIEDAD POR ACCIONES SIMPLIFICADA":"C01599","CASTELLA GABRIELA CECILIA":"C00978","CLAUDIO CUMIN LEONEL":"C01479","COMERCIAL FEYRO":"C00028","DIMOTEC SA":"C02220","E.M.E. S.R.L.":"C01673","ELECTRO COUNTRY S.A.S.":"C02803","ELECTROSUR S.R.L.":"C00399","FLOWELEC S.A.S.":"C02769","FRANKE OTTO GUILLERMO":"C02467","GENERCO S.A.":"C02708","INVERSIONES COMERCIALES S.A.":"C02089","LOS MOLINOS SRL":"C01668","LUBEAL S.A.":"C00795","LUCCATTO ELECTRICIDAD S.A.S.":"C01588","LUIS MALPASSI ELECTRICIDAD S.A.":"C01678","LUMINARE S.A.S.":"C01266","MACSOL S.A.S.":"C02271","PARRA FLAVIO BENJAMIN":"C00715","POWER ELECTRIC S.A.":"C02020","PRODEL S R L":"C01657","RADIO ELECTRON S.A.":"C00441","RIVERA CRISTIAN HERNAN":"C01423","TANGENTE GROUP S.A.":"C00255","TELEFONIA FRANCIA S.A.":"C01381"}},"ALEXIS GONZALEZ":{"clientes":{"AG INSTALACIONES SRL":"C02118","ALKO SRL":"C01521","AM ENERGIA CONECTADA S.R.L":"C01962","AMBAR ENERGIA S.A.S.":"C01768","ARNET ILUMINACION S.R.L.":"C01797","ATILA GENERACION S.R.L.":"C02804","BAIRESTRON S.R.L.":"C01870","BRAUNCO SAU":"C02091","CANTANDO MARCELO NICOLAS":"C02114","CM SERVICIOS ELECTROMECANICOS S.R.L.":"C01788","CONTECO S R L":"C01487","DINAMO MATERIALES ELECTRICOS S. A.":"C02317","DYNAMIC ENERGY SOLUCIONES ENERGETICAS":"C01354","ELECTRIC SYSTEMELEC D&M ARMIENTO Y GARRIDO S.R.L.":"C02824","ELECTRICIDAD PANAMERICANA  SA":"C00396","ELECTRO HCM S.R.L.":"C02300","EMELINT S.R.L.":"C01966","ENERGIA CONTROLADA S.R.L.":"C01765","ENERGIA LIMPIA S.R.L.":"C01744","ENEXAR S.R.L.":"C01307","ERNESTO JORGE RAFAEL":"C01724","ESINEL S R L":"C02561","FACOEL ARGENTINA S.R.L.":"C01642","FARLO SOLUCIONES ELECTRICAS S.R.L":"C02047","FERNANDEZ ILUMINACION SRL":"C02793","GIANICO BRUNO ALEJANDRO":"C00581","GLOBAL INGENIERIA CONSTRUCCIONES Y SERVICIOS SRL":"C02113","GRUPO SIEI SRL":"C01778","HOCH ASCENSORES S.R.L.":"C01510","ISEM SA":"C02689","LA ELECTRICA SRL":"C01968","LEONI LUCIANO":"C01873","MJG S.A.S.":"C02544","MULTI RADIO SOCIEDAD ANONIMA":"C01955","MULTISOLAR S. A.":"C02227","ORIENS ENERGIA":"C01772","PAZOS ALEJANDRA EDITH":"C01934","PODER ELECTROMOTRIZ S.A.S.":"C01613","PROF INSTALACIONES S.R.L.":"C01890","ROMBOLA FERNANDO GABRIEL":"C01689","RST SOLUCIONES INDUSTRIALES S.A.":"C01872","SHEELEC INGENIERIA S.A.":"C01844","SOLUMAX S.A.S.":"C01436","SOMARFER S A":"C02704","SUMAR SERVICIOS INDUSTRIALES S.R.L.":"C01489","Suministros Electricos Especiales SRL":"C01350","TESBAR S. R. L.":"C01518","VEOLIA SERVICIOS Y GESTION DE ENERGIA ARGENTINA S.A.U":"C01393","VIDARCO S A":"C02536"}},"ALFREDO CASTRO":{"clientes":{}},"ANDRES O'BRIEN":{"clientes":{"ALUMINIO SALTA S.R.L.":"C00347","ATIEMPO SEGURIDAD S.R.L.":"C02267","AÑO LUZ HORIZONTE":"C00471","BASSANI CARLOS ENRIQUE":"C00300","BIM S. R. L.":"C01995","BP SOCIEDAD ANONIMA":"C00316","CASTELBIANCHI HUGO MARCELO":"C00409","CERETTI ALFREDO MIGUEL":"C01224","CHAILE GABRIEL OSVALDO":"C01564","CJ ELECTRICIDAD SH DE CORONEL":"C00600","CONDORI PASCUAL ROBERTO":"C02559","CRISALIS S. R. L.":"C02506","DIMATER S.A.":"C00952","DOS VEINTE S.R.L.":"C01210","DYMA ELECTROCOMERCIAL SRL":"C01265","E J E  S A":"C01812","ECQ S. R. L.":"C02145","ELECTRICIDAD TITO S.A.S.":"C01703","FELIPE JOSE IGNACIO":"C01746","FELIPE LA LLAVE S. A. S.":"C02697","FELTRIN SA":"C01067","GEOMACO S.A.S.":"C01319","GONZALEZ RODOLFO JOSE":"C01961","HIPERCAT S.A.S.":"C01721","HORIZONTE SRL":"C00813","JOZAMI PABLO GONZALO":"C02642","KILOWATT SRL":"C01399","LEANDRO G CAMPOS":"C01240","LINEAS ELECTRICAS SA":"C01530","LUXING S.R.L":"C00543","MERAKI S. R. L.":"C02479","NEO GROUP S.R.L.":"C00605","NOALED S.R.L":"C01135","PAEZ RAMON ANTONIO":"C01866","PALUN SRL":"C00801","POSITRON S. R. L.":"C02312","RAITO S. R. L.":"C02028","ROMULO VALDEZ":"C01851","ROVI S.R.L.":"C00299","SANTIAGO KOHN S.A.":"C00602","SUPERMAT CENTRAL S.A.S":"C01923","ZATEC SOLUCIONES SAS":"C02049"}},"CLAUDIO SUAREZ":{"clientes":{"HERRAMIENTAS PERGAMINO S.A.":"C02652"}},"DANIEL HERRERA":{"clientes":{"COTO CENTRO INTEGRAL DE COMERCIALIZACIîN SOCIEDAD ANîNIMA":"C01836","DISTRIBUIDORA MAS DEL NORTE S. R. L.":"C02691","FALABELLA S.A":"C00668","SCARFONE DOMINGO CARMELO":"C02739","SUPERMERCADOS MAYORISTAS MAKRO SA":"C01609"}},"DEBORA PERILLI":{"clientes":{"ADELECTRIC SRL":"C00510","ARSA ELECTRICIDAD SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C02146","BASSO MICAELA":"C02466","CANAL ELECTRIC S.A.":"C00301","CASA LEO MAT. ELECTRICOS SRL":"C00626","CEIJA PABLO EDUARDO":"C02696","DASEL SRL":"C01586","DEFRANCO YANINA VERONICA":"C02657","DEL BONO MONICA ADRIANA":"C01930","DISCUALCO SOCIEDAD ANONIMA":"C01149","ELECON ARGENTINA S.R.L.":"C01711","ELECTRICIDAD CORNEJO":"C02425","ELECTRO 202 S.A.":"C02405","ELECTRO MEDINA":"C00929","ELECTRO PERBE":"C00576","ELECTROAMBAR SRL":"C00533","ELECTROAR ELECTRICA AVANZADA LUJAN S. R. L.":"C02851","EXALUZ S.S":"C01276","GIOIOSA DONATO ALBERTO FABIA":"C02505","GRUPO ALR S.R.L.":"C02391","GUARPOIC SOCIEDAD ANONIMA":"C02789","IBALDI PABLO DANIEL":"C02169","ILUMINAIRES SRL":"C01663","ILUMINANDO DE CASELLA HEMILCE":"C00718","MAQUINAS ALCORTA S. CAP I SECC IV":"C02409","MARINO SANDRA EDITH":"C02450","MASER ELECTRO SA":"C02417","MAYORISTA ELECTRICO JALACA SA":"C02229","MICELI CARLOS ANTONIO":"C02452","MONTENEGRO WALTER MIGUEL":"C00207","NUOVO ROMA SRL":"C00431","OESTE LED S.R.L.":"C02338","OSCAR GARCIA Y VERONICA MEZA SOCIEDAD DE HECHO":"C01612","PRONTO ELECTRICA SRL":"C01235","PROVEEDOR INTEGRAL DE MATERIALES ELECTRICOS S.A.":"C02390","RIVERO GONZALO MARTIN":"C02555","SANCHEZ PEÑALOZA GUSTAVO RAUL":"C01466","SARELEC":"C01188","SUAREZ CRISTIAN SEBASTIAN":"C01824","SUAREZ FERNANDO EZEQUIEL":"C02439","TIMARO SRL":"C02396","URBANO APS S.A.":"C02342","VITIENES MARIA LUISA":"C02337"}},"EMMANUEL GIORGIO":{"clientes":{"ALBERTO MORRA S.A.":"C02610","AMADO IGNACIO":"C01732","AMOORA SOLUCIONES":"C02540","CABLE A TIERRA SRL":"C01950","CASA EDEL S.R.L.":"C01660","CHERVO BRIAN NAHUEL":"C01967","CLEMENZ GASTON RENE":"C02465","DE LIMA NILDA ESTHER":"C02168","ELECTRICIDAD DER S.H.":"C00521","ELECTRICIDAD PARANA S.A.":"C00564","ELECTRO LIDER S. R. L.":"C02256","ELECTRO UNO S.A.":"C01629","ESPINOSA CARLOS MATIAS":"C02170","GABRIEL NICOLAS KOCH":"C01234","GOETTE DIEGO HERALDO":"C01699","GRDEÑ CARLOS MAXIMILIANO":"C01432","INNOCENTI YAMILA DE LOS MILAGROS Y PIGNATTA MAXIMILIANO":"C01589","KRAUSE NORBERTO":"C01186","LA CASA DEL ENCENDIDO S.R.L.":"C01184","LUZIN S.R.L.":"C01954","MAINA HECTOR HUGO":"C00631","MULTIMAT- A.C.E.":"C01727","NEIS NICOLAS":"C01191","NEXUS SRL":"C02322","NOBILE FLAVIA ROCIO":"C02410","PASSARELLO MATIAS":"C01424","QUAIN RADIO SA":"C01723","RED ELECTRO PUNTO S. R. L. EN FORMACION":"C02534","SARTORI GERARDO ARIEL":"C02557","TAMALET CRISTIAN EMANUEL":"C00988","TECNOLOGIA EN ELECTRONICA Y CONTROL S.R.L":"C02807","TRANSELEC S R L":"C02004","VICTOR J BUSSO S A":"C01939"}},"EZEQUIEL MAYAYO":{"clientes":{"ALEJO DIAZ MONTAJES ELECTRICOS S.R.L.":"C01976","ALTECNIA S.R.L.":"C01568","BETTENDORFF S R L":"C02088","CANTHI INGENIERIA S.R.L.":"C01777","CONTOMATIC SOCIEDAD ANONIMA COM IND Y FIN":"C01906","CPI & T SRL":"C01911","CRYGA":"C01933","ELECRIS S.R.L.":"C01434","ELECTRO PANDORA SRL":"C02547","ELECTROINGENIERIA I.C.S.S.A.":"C02135","ELECTROMECANICA CONELEC S.A.":"C01492","FA SOLUTIONS SRL":"C01863","GISKAR SRL":"C01761","GVME S.A.S.":"C01864","HORMETAL SA":"C02339","IN. COLOMBO SA":"C02187","INTEGRAL 9 S.R.L":"C01917","J G ELECTRICIDAD SRL":"C01820","LA INDUSTRIAL ELECTRICA S A":"C02670","LOBOS SANTIAGO OSCAR":"C02245","MATERIALES ELECTRICOS GRECO SR":"C00121","MEHCCO S.A.":"C01903","MISKOWIEC SILVIO CESAR":"C02165","MYTEC S R L":"C01970","PROSEL MONTAJES S.A.":"C02077","Q ELECTRIC S.R.L.":"C01902","RISTAL SRL":"C01309","SANFERELEC SA":"C02593","SERVICIOS Y ASESORAMIENTOS ELECTRICOS S A":"C01779","SERVINEL S A":"C01912","SILOGIC  S.R.L.":"C02553","TECNEL   ELECTROTECNICA   S.A.":"C01569","TECNIARK SA":"C01543","TECNICA ELEMEC S A I C I Y A":"C02548","TECNICAS MODERNAS APLICADAS SA":"C01905","TIPEM S.A.":"C01506","VALLE INFERIOR S.A.":"C00840"}},"EZEQUIEL QUEVEDO":{"clientes":{"AMAVI S. A. S.":"C02316","ASELEC S R L.":"C02280","ATELEC S.A.":"C00538","BIWELL S.A.S.":"C02069","COOP. DE ELECT Y OTROS SERV DE MERCEDES SAN LUIS LIMITADA":"C00374","CORPUS S.A.":"C00371","DISTRIBUIDORA 370 SOCIEDAD ANONIMA":"C01734","DISTROELECT S.A.":"C01654","ELECTROMECANICA PERICH SAS":"C02269","FAS ELECTRICIDAD S.A.":"C00376","FERRELEC MENDOZA SA":"C00373","GENCO MATERIALES ELECTRICOS SA":"C00517","INVERSORA DEL OESTE S.R.L.":"C00328","Ingeniería y Materiales SA":"C01246","LUNA S.R.L.":"C02537","MATERIALES FTP SOCIEDAD ANONIMA":"C01509","POL GABRIEL BARTOLOME":"C01821","SERVICIOS ELECTROMECANICA INDUSTRIAL SRL":"C02404","TIRENTI GERARDO JAVIER":"C01945","TRIELEC SA":"C00398","VECINO GUSTAVO FABIAN":"C02341","ZANON MARIA PILAR":"C02681"}},"FABRICIO VIRZI":{"clientes":{}},"FACUNDO JORRAT":{"clientes":{"20X20 S.A.":"C02518","ABDALA ILIES HASSAN":"C02694","ALDERETE MARCOS EDUARDO":"C02783","ANFRA S.R.L.":"C02701","ARGAÑARAZ RODOLFO HORACIO":"C02401","BARRIONUEVO ESTEBAN MANUEL":"C02459","BERNARDI SRL":"C02706","BOGGO MARIA EUGENIA":"C02750","BOLLINI S A":"C02714","BULONERIA REGINATO S.R.L.":"C02835","CAMPOFOSCO MARTA GRACIELA":"C02451","CANIVARES PAZ OSCAR MARTIN":"C02463","CANO ARON JOSE VICTOR":"C02526","CERVERA MARIA SILVINA DEL VALLE":"C02460","CLINKERS S. R. L.":"C02724","COMERCIAL COLON E M  S R L":"C02556","CORDOBA NGG GROUP S. R. L.":"C02636","DEL RIO JOSE DANIEL":"C02792","DIAZ ENRIQUE DANIEL":"C02552","ELIAS PABLO EXEQUIEL":"C02387","ESPINOSA ANDRES ANTONIO":"C02530","FERNANDEZ CESAR ANDRES ALEJANDRO":"C02703","FERREKIT S. A. S.":"C02414","FIDEICOMISO AVITA":"C02418","FONTANA OSCAR ALFREDO":"C02443","GIL TOMAS ENRIQUE":"C02612","GOMEZ ESTER MERCEDES":"C02635","GONZALEZ FRANCISCO AGUSTIN":"C02579","GONZALEZ ROMINA AGOSTINA":"C02725","GRUPO ALBORNOZ REINA SRL":"C02639","HERNANDEZ SILVIA ESTELA":"C02752","IMAGEN & SERVICIOS EMPRESARIALES SRL":"C02621","JASAK S.R.L.":"C02623","JUAN MIGUEL JACINTO":"C02444","L.A.I.C. SRL":"C02503","LA FERRETERIA S.R.L.":"C02622","LERDA MARIA PIA":"C02684","LO BRUNO SOCIEDAD ANONIMA":"C01895","MARQUEZ MIRIAM ANALIA":"C02776","MASMUD RICARDO ALFREDO":"C02395","MDALEL CABALLERO MIGUEL ALEJANDRO":"C02461","MEDICI Y CIA S.R.L.":"C02723","MIGUEL LUCIANO RAMIRO":"C02707","OBERMANN EDGARDO MATIAS":"C02846","OBERMANN ENRIQUE SAMUEL":"C02722","PALOMO ANGEL EDUARDO":"C02462","RECAMAT S. A. S.":"C02500","RENFOR SOCIEDAD SIMPLE DE RENDACE FORTINO JAVIER MAXIMILIANO Y RENDACE FORTINO CRISTIAN GABRIEL":"C02394","RIWER REPUESTOS S. A. S.":"C02782","ROMANO SERGIO RAUL":"C02600","RP CONSTRUCCIONES SRL":"C02343","SANIN DIEGO":"C02702","TRANSPORTE MARTINEZ S. A. S.":"C02685","VAAMONDE PABLO JAVIER":"C02719","VARGAS LOBO FACUNDO MARIANO":"C02585","VILLAFAÑE MARIA ELENA":"C02413","YUHMAK SEGURIDAD INDUSTRIAL S.R.L.":"C02412","ZELARAYAN RICARDO JOSE":"C02712"}},"FRANCISCO BOERO":{"clientes":{"ACCMELEC SAS":"C02598","ANDREA FABIANA ANDREONE":"C00754","BORELLO HNOS S.A":"C00748","CARLOS CESAR PANESSI":"C00740","CASTEX GROUP":"C02141","CHI YA TING":"C01563","CHIABUDINI CASTRO S H":"C01694","DIGITO BINARIO S R L":"C02643","ELECTRIC HOGAR SRL":"C01542","ELECTRICIDAD SOLARI S.R.L.":"C00425","ELECTRO DESCUENTO SA":"C01311","ELECTROPEREIRA 22 S.A.":"C02234","ENLUZ SA":"C01038","FERRETERIA ANTARTIDA SOCIEDAD LEY 19550 CAPITULO I SECCION IV LGS":"C02012","FERRETERIA PLATENSE SCABUZZO E HIJOS SRL":"C01475","GALLUCCI SA":"C00325","GALPIZ S.R.L. S. R. L.":"C02841","GALUSS":"C00073","GARCIA FERNANDO GABRIEL":"C00375","GONZALEZ SORIA FACUNDO":"C01882","ILUZ SOCIEDAD ANONIMA":"C01736","IMPORTADORA FC S.R.L.":"C02795","JALUX S.R.L.":"C01415","JLF MATERIALES ELECTRICOS SA":"C00094","JOSAFAT SRL":"C00776","JOSE ANDREA LETICIA":"C00985","JOSE LUIS ARELLANO":"C00750","KUMRU SEBASTIAN":"C00934","LGLUZ S.A":"C00537","MCJR S.R.L.":"C01583","PARONZINI LEONARDO GASTON":"C00802","PASCO COMERCIAL SA":"C00735","POLO & LUZ S.A.":"C02268","PROCAN MATERIALES ELECTRICOS":"C01058","STARX SECURITY S.R.L.":"C02260"}},"FRANCISCO RAWSON":{"clientes":{"ALANIS MARIANO ESTEBAN":"C02471","ALLENDE OSCAR RAMON":"C02456","ANGELONI DIEGO RAMON":"C02668","ARGAÑARAZ JUAN GABRIEL":"C02143","BETRES SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C02483","BITOMA S.R.L.":"C01604","BULONERIA Y FERRETERIA INDUSTRIAL MORENO S.R.L.":"C02407","CAIRO SANTINO":"C02651","CAVISEMI S.A.":"C02105","CEOSSEG S.R.L.":"C02209","COGNIGNI JUAN CARLOS Y COGNIGNI LEANDRO MAURICIO S H":"C02731","CORNIER VICTORIA SOLEDAD":"C02806","DECURGEZ KARINA ALEJANDRA":"C02216","DURBECK S.R.L.":"C01333","EL HOGAR OBRERO FERRETERIA S. R. L.":"C02672","FERRETERIA LA INDUSTRIAL S.A.S.":"C02406","FERRETERIA UDINE DE CISILINO MAURO ADRIAN Y GARRALDA MARIANO ABEL":"C02599","GRESCHUCK SPATARO RICARDO JAVIER":"C02065","JANCICK WENCESLAO JAVIER":"C02295","JOSEPH MARCOS":"C02207","KELCOM  SRL":"C02082","L. MARINAS S.A.":"C02641","LETRATEC SA":"C00665","MAQUINAS Y HERRAMIENTAS CAIRO S.A.S.":"C02252","MARTIN MARCELO SERGIO":"C02232","MARTINEZ GERMAN LUIS":"C02565","MASTANDREA MABEL MARIA DEL C":"C00022","METALURGICA DUROLL SRL":"C02496","PANDOLFINI HNOS. S.R.L.":"C02618","RAMOS MARCELO GUSTAVO Y RAMOS GUILLERMO NESTOR":"C02171","REPARE ARGENTINA S A":"C01142","ROBLES JOSE MARIA":"C02507","ROCNET":"C02478","RODRIGUEZ EZEQUIEL MARCOS":"C02673","SALA FRANCO TOMAS":"C02304","SALIBE AGUSTIN MARIO":"C02586","SCHAFFNER MAGDALENA":"C02655","SEATRADERS SRL":"C02272","SOLUCIONES ELECTRICAS AVANZADAS":"C01066","TECNOHOGAR S.A.":"C02147","YACOPI GUSTAVO RODOLFO Y GAFARELO MARCELO DANIEL SOCIEDAD SIMPLE LEY 19550 CAP. I SECCION IV":"C02674","ZAMBRANO VARGAS JASMIN YULIANA":"C02525","ZAPICO FACUNDO ALCIDES ROVER":"C02287"}},"FRANCO LAUCELLA":{"clientes":{"EMPRESA DISTRIBUIDORA DE ELECTRICIDAD DE MENDOZA SOCIEDAD ANONIMA":"C01416","EMPRESA PROVINCIAL DE ENERGIA DE CORDOBA SOCIEDAD ANONIMA UNIPERSONAL":"C01388"}},"JERONIMO GALAN":{"clientes":{"AFME S.A.":"C00679","CABRERA EDUARDO FABIAN":"C00911","CALVO RODRIGO ALEJANDRO":"C02066","CORTES ANA MARIA":"C00211","DISEÑO EN ILUMINACION SRL":"C00382","DISTRIBUIDORA NORTE S.A.":"C01833","ECO ENERGIA SRL":"C01515","ECOELECTRO S. A. S.":"C01899","EL ADI JULIO CESAR":"C01113","ELECTEC S.A.":"C01357","ELECTRICIDAD MAZA SRL":"C01197","ELECTRO 3 SAS":"C02307","ELECTRO CUYO S. A.":"C02711","ELECTRO DORREGO S.A.":"C00346","GRUPOFAS S.A.":"C00944","LUZ CUYANA S. A. S.":"C01661","MAS ELECTRO URQUIZA S.A.":"C00297","MIGLIORISI CLAUDIO MARCELO":"C02130","MOCOROA SOCIEDAD ANONIMA":"C01986","MOTELEC S R L":"C02217","MOTORES Y MATERIALES ELECTRICOS SA":"C00332","OFME S.A.":"C00345","PERFIL S.A.":"C01937","RESI SRL":"C00306","S.I.E.B. ELECTRIC. S.A.S.":"C02027"}},"LEANDRO VAZQUEZ":{"clientes":{"NIETO JORGE EDUARDO":"C02493","RASELLI HECTOR ATILIO":"C02520","TODOMAQ SRL":"C02475"}},"MARCOS LATORRE":{"clientes":{"ARGELEC CENTRO S.R.L.":"C00225","CRICHIGNO, SEBASTIAN EDUARDO":"C00502","DEKKO GUALEGUAYCHU SRL":"C02080","DON LUCIANO":"C00935","DUCA ORLANDO RUBEN":"C02270","DURAND HECTOR JOSE":"C01691","EL ALMACEN FERRETERO S.R.L.":"C02533","ELBIO RAUL GOMEZ":"C00687","ELECTRICIDAD COLOMBO SA":"C00555","ELECTRICIDAD SERRA SRL":"C00273","ELECTRINET SRL":"C01486","ELECTRO AGUIRRE":"C00870","ELECTRO MAS SRL":"C01850","EMILIANO GERMAN GOMEZ":"C00960","FIOCCHI PABLO DAMIAN":"C02022","GALAN ALEJANDRA":"C00271","GUERRERO ELECTRICIDAD SRL":"C00703","GURINA SRL":"C00534","HERNANDEZ ANGEL ANTONIO":"C00966","HORACIO R ROSVIAR":"C01849","INGANI ALBERTO RAMON":"C01237","INGENIERIA BOGGIO SA":"C01055","JUNELEC":"C00765","MARTIN GABRIEL ADALBERTO":"C01181","MASTRANGELO PRODUCTOS ELEC SA":"C00704","MOZZONI PORTA ARGELEC SA":"C00625","OTTAVIAN DANIEL GERMAN":"C01176","RADIO LUX S.A.":"C01469","RAMIRO ARGENTO":"C00839","RIGELEC S.R.L.":"C01170","SCHULTHEIS ALCIDES P.I SANTIL":"C00251","SIRC ILUMINACION":"C00224","SOSA GUERCI MIRKO":"C01801","SUCESIÓN DE LUIS MARIO RAMPELLO":"C00222","TECCE":"C00216"}},"MARIANO BOTTA":{"clientes":{"ABONS CECILIA ADRIANA":"C02302","BARILA GUSTAVO G Y PITTALUGA MARCELO E SDE HECHO":"C00565","BERTOLA CARLOS JAVIER":"C00831","BERTOLA MATIAS":"C00991","BULACIO MIRIAM LILIANA":"C01974","BURNE DANILO":"C00442","BUSTAMANTE CARLOS ALBERTO":"C02093","CALRAD BOLTON S.A.":"C01846","COMUNICACIONES EMPRESARIALES SRL":"C01695","DACROCE S.R.L":"C00036","DANIEL AGRELO & CIA. S.R.L.":"C02157","ELECTRICA SAYCO S.A.":"C02737","ELECTRICIDAD DALUZ  SRL":"C02198","ELECTRICIDAD GABRIEL SA":"C00546","ELECTRICIDAD HAEDO SACIFA":"C01364","ELECTRICIDAD SAN MARTIN SA":"C01096","ELECTRO SELEC":"C00056","FERRETERIA INDUSTRIAL HC S.R.L.":"C02455","FOL MATERIALES ELECTRICOS  S. R. L.":"C01860","GAMA MATERIALES ELECTRICOS S.R":"C00074","GOTA DE PIEDRA S.A.":"C01454","GRUPO FELIPA SAS":"C01253","KYMAT S. R. L.":"C02249","LED-MORON S.R.L.":"C02009","LUMIFLEX S.R.L.":"C00834","M-ELEK SA":"C01452","MERAGLIA DANIEL RICARDO":"C00518","MICCICHE RUBEN HUGO":"C01805","MONARDO ALEJANDRO JAVIER":"C00559","NARDONE ALDO":"C00868","ORONEL HECTOR JAVIER":"C00828","PAZ MYRIAM ELIIZABETH":"C00588","PEDRAZZINI MONTOYA FELIPE Y MO":"C01077","PROVELEC SA":"C01380","QUIÑONEZ AGUSTIN":"C01292","QUIÑONEZ LAURA DANIELA":"C02013","RODINO CRISTIAN MANUEL":"C02070","RODIÑO ALEJANDRO":"C01334","SMART IT SOLUTIONS S.R.L":"C02688","SOVERNA ALICIA":"C00807","VEGA LUCAS EMMANUEL":"C02002"}},"MARIANO SCHULTZE":{"clientes":{"MIX MASTER MAQ":"C02480"}},"MAXIMILIANO CORNIOLA":{"clientes":{"BARTOLI JOAQUIN SERGIO":"C01272","BONGIORNO JOSE LUIS":"C00444","BRANA HERMANOS SOCIEDAD ANONIMA":"C01567","C Y L ELECTROMATERIAL S A":"C01431","CASA MAGNANI SRL":"C01204","CORDOBA ELECTRICIDAD E ILUMINA":"C00030","CPT INTEGRAL SA":"C02159","DE ROSA MATERIALES ELECTRICOS CALCHAQUI S.A.":"C02424","DEMALEC SA":"C00736","DI-PER ELECTRICS":"C02079","DIAZ GUSTAVO ADOLFO":"C01665","DILUVA GROUP S.R.L.":"C02399","EBERT A BERTORA SA":"C01317","ECKERDT ROBERTO FELIPE":"C01417","ELECTRICIDAD 23 S.R.L.":"C02853","ELECTRICIDAD ALSINA":"C00047","ELECTRICIDAD DEL SUR  SA":"C00904","ELECTRICIDAD DELFINO":"C00760","ELECTRICIDAD MIGUEL S.A.":"C00364","ELECTRICIDAD RAMOS MEJIA S R L":"C02246","ELECTRICIDAD SAN PEDRO DE PEREZ MARIO Y SILVIA":"C01398","ELECTRO DRF S.R.L.":"C01658","ELECTRO MB SRL":"C02127","ELECTRO ROQUE PEREZ SOC. SIMPLE DE PESARESI LEONARDO, PESARESI ANA JULIA Y ROSALES ALEJANDRO":"C01794","ELECTRO-DOS SA":"C00585","FEVESA CAÑUELAS SRL.":"C01435","GL MATERIALES ELECTRICOS":"C01762","GRILLO SERGIO GUSTAVO":"C02535","GRUPO CALA SA":"C02313","HURIN S.R.L.":"C02554","IVANI ARIEL EMILIO":"C01433","LUMINARIAS OESTE SA":"C00767","MARIA CABRERA S.R.L.":"C02335","MENDOZA QUISPE BRYAM JEREMY":"C01880","MENESES HUGO SERGIO":"C00877","MITRE ELECTRICIDAD SRL":"C01218","OBRECHT GERMAN ANDRES":"C02283","PAYO Y CIA SRL":"C00361","PEM PRODUCTOS ELECTRICOS S.A.":"C01835","PERTINO TOMAS":"C02644","RAMIREZ STAGNO MAYRA WALQUIRIA BELEN":"C01780","SOMARKET SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C01593","SOULE S A COM E IND":"C02308","SUSTEN MARKET - ECO SHOP SRL":"C01829","TOFEMA SA":"C00418","TORTONESI DANIEL ALEJANDRO":"C00339","VENTMAEL S. R. L.":"C02453"}},"NICOLAS GIORDANI":{"clientes":{"AC ELECTRICIDAD S. A. S.":"C02098","AK MATERIALES ELECTRICOS S.R.L.":"C01420","ARTELCO S.R.L.":"C00234","AÑOS LUZ SA":"C00230","BIM  S. A. S.":"C02298","BLACK SHEEP S.A.S.":"C01580","DDMM ENERGIA S.R.L.":"C00998","ED-MAR ELECTRICIDAD S.A.":"C01064","ELECTROBRAS S.R.L.":"C00592","ELEKTRA.NQN SRL":"C02532","ENERGIA SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C01683","EQUIPEL SRL":"C00615","GRS PATAGONICA SRL":"C00561","LAUTREC ILUMINACION SRL":"C00453","MARINI Y CIA SRL":"C01304","NEOLED SRL":"C01223","NQN ILUMINACION S.R.L.":"C00133","NUEVO SUR S.A.":"C01216","PASTORUTTI S.A.":"C01760","RODRIGUEZ ROBERTO CRISTIAN":"C00438","SALINAS HECTOR MIGUEL":"C01374","SMA ILUMINACION S.R.L.":"C01145","STROIA ELECTRICIDAD S.R.L.":"C02108","TODOLUZ DISTRIBUIDORA DE COMP":"C00436","UNELEC S.A.":"C01823","Z ELECTRICIDAD S.A.":"C00372","ZUKAS S.R.L.":"C00915"}},"NICOLAS RACCA":{"clientes":{"ANTUNES JUAN IGNACIO":"C02448","AV INGENIERIA S.R.L.":"C02257","BLANCO GRUP":"C01579","BUSS MARISA FANI":"C02523","CASA BLANCO SA":"C00816","CENTRO ELECTRICO BARILOCHE S.R.L.":"C01791","CHIAPPA CRISTIAN DARIO":"C01363","CIAPPINA MAURICIO JAVIER":"C00872","CONSTITUCION 4901 S.R.L.":"C02656","CULACCIATTI HILDA MABEL":"C02265","DISTRIBUIDORA BAUDRACCO SA":"C00253","DISTRIBUIDORA LAELEVC S. R. L.":"C01815","DR ARRECIFES SA":"C01559","DUMTRAX S.R.L.":"C02514","ELECTRICIDAD JUNIN SA":"C00397","ELECTRICIDAD LAVALLE S.R.L.":"C01574","ELECTRICIDAD MECA S.A.":"C01809","ELECTRICIDAD TOTAL S.A.":"C00815","ELECTRICIDAD USHUAIA SRL":"C00053","ELECTRO INTEGRAL VILLEGAS S.H.":"C00847","ELECTRO STOCK S.A.":"C00057","ELECTRO SUR DE VITOLA CLAUDIO ENRIQUE Y VITOLA DIANA":"C02464","ELECTRONICA CHIVILCOY S.A":"C01049","EVOLUCION INTELIGENTE BY ELECTROM S.R.L":"C02099","FASE 3 DE DIEGO ENRIQUE CORIA,MAXIMILIANO DAMIAN CORIA Y YESICA VANESA PEREZ DE ALESANDRE":"C01822","FERRIOL JULIO MIGUEL":"C01993","FG INDUSTRIAL SH":"C00931","FONTFREDA HNOS. S.A.":"C00194","FS TECNICA INDUSTRIAL SRL":"C02050","GARCIA MATIAS MARIANO":"C00874","GESELEC1380 S.R.L.":"C02777","HORACIO RUBEN OLTHOFF":"C00059","INDUSTRIA LUMINICA ARG":"C01274","JORGE E SUAREZ S.A.":"C02743","JUMAELECTRIC  S.A.":"C00984","KETO BARCO S.R.L.":"C00235","LBT ELECTRICIDAD TRES ARROYOS":"C00894","MARCOS ANDRES IACOMELLA":"C00672","MARCOVICH BRAIAN":"C01314","MARIO OSCAR SENSI E HIJOS SH":"C00945","MATELEC SA":"C01000","MECAN SOCIEDAD ANONIMA":"C02823","MELLUSO ELECTRICIDAD S.A.":"C00928","METALTRONIK AUTOMATIZACION INDUSTRIAL S.R.L":"C02259","MEZA GUILLERMO ALBERTO":"C01091","NEA-ELEC S.A":"C01693","NICOLAS A SANTANA MARRERO":"C01023","O.A.C.I. S.A.":"C00268","OFFICIALDEGUY ALEJANDRO":"C00886","OLIVA RICARDO GABRIEL":"C00809","PABLO EZEQUIEL ROMERO":"C00973","PASCUAL GASTON JESUS":"C01047","PASSARINI ALEJANDRO OMAR":"C01400","PLE BRAGADO S.A.":"C00963","PROYECCION ELECTROLUZ SRL":"C01594","ROMELEC  S. R. L.":"C01963","S.C.H. GROUP S.R.L.":"C02299","SANTINI CLIVIO S.R.L.":"C01037","SINGLA ELECTRICIDAD S.A.":"C01631","TAMEX2 S.A.":"C02223","TECNOELECTRICA S.A.":"C01385","TIMU S.A.":"C01004"}},"OSCAR LOPEZ":{"clientes":{"AUTOMOTORES PALET S.A.S.":"C02778","BLANDA PABLO DANIEL":"C02476","CAO JORGE HERMINIO":"C02699","CAPATTI ARIEL HERNAN":"C02660","CONCRET S. R. L.":"C02690","CONTEGNOSO CARLOS LUIS":"C02695","ECA DISTRIBUCIONES S.A.S":"C02700","EL KIMU S.A.":"C02595","ENRIQUE R. DICK Y CIA. S. R. L.":"C02613","FONPER S R L":"C02495","GALLARDO MARIANO GABRIEL":"C02626","GOMEZ LUIS ALBERTO":"C02683","GUTIERREZ ANDRES B MANETTI LIDIA C GUTIERREZ ROMINA Y GUTIERREZ GUSTAVO A SOC SIMPLE":"C02481","KASA S. R. L.":"C02717","LUJAN AGRICOLA SRL":"C02666","MALANCA AGROMAQUINARIAS S.R.L.":"C02647","METALES DIBO S A":"C02716","OXIGENO ALVAREZ S. A. S.":"C02693","PEREZ ROSSI JAVIER GUSTAVO":"C02638","PONCE FABIO ROMAN":"C02609","RED FERRETERA S.A.":"C02692","SAVORGNANO SEBASTIAN":"C02648","SURI S. A.":"C02665","ZAMARIAN LEANDRO ARTURO":"C02654"}},"RICARDO GISMONDI":{"clientes":{"ADALBERTO DELFINO PAPP":"C00771","ALBORNOZ JORGE RAUL":"C01097","BELLINI ELECTRICIDAD S.R.L.":"C00258","BRUNEL ELECTRICIDAD S.A.":"C00337","CACEREZ PEDRO DIEGO EUGENIO":"C01549","CASA AIDES SA":"C00190","CASA PASTOR SRL":"C00818","COMPAÑIA ELECTRICA SRL":"C01348","DOMINGO CARLISI & CIA S.R.L.":"C01725","ELECTRICIDAD CENTRO S.A.":"C01052","ELECTRO JUNIN SRL":"C01050","ELECTRO LINEAS SA":"C01965","ELECTRO MISIONES SA":"C01422","ELECTROMAR SRL":"C00525","HENAIN MARIELA NOEMI":"C01205","LA LUCERIA S. R. L.":"C01999","MENDOZA ADOLFO DANIEL":"C01800","MIGSA SOCIEDAD ANONIMA":"C01958","NEALED SRL":"C00737","PROKOPIUK Y CIA S R L":"C02509","RAMOS JULIO JAVIER":"C02698","TTP MATERIALES ELECTRICOS S. R. L.":"C02392"}},"RODRIGO ZANABRIA":{"clientes":{"AREVALO SIMON ARTURO":"C02822","CARCAR DANIEL ALEJANDRO":"C02810"}},"SANTIAGO LEZAMA":{"clientes":{"CAROLINA LAURA IBARRA PIERDRAB":"C01260","CASA CASTELAO S A":"C01561","CLS ELECTROMATERIALES":"C00888","D LED SH":"C00217","E. C. LIGHTING S.A.":"C01557","EL FARO RECOLETA S.R.L.":"C01715","ELECTRICIDAD HM SRL":"C00959","ELECTRO DIEL S R L":"C01402","ELECTRO FLEMING S.R.L.":"C00511","ELECTRO INDUSTRIAL LYNCH SA":"C02011","ELECTRO UNIVERSO SA":"C01233","ELECTRODUK S.R.L.":"C00854","ELECTROLED S.A":"C01020","ELECTROMILENIO SRL":"C01251","FABELEC SAS":"C01125","FULL ELECTRIC SRL":"C00787","GRIM S.A.":"C01017","ILUMINACION AGUERO":"C01030","INDUS ELECTRIC SA":"C00729","INSTALACIONES ELECTRICAS RAYO":"C00835","JN FABRICA ELECTRICA SOCIEDAD ANONIMA":"C01525","KING SMIT CLAUDIO GUSTAVO":"C00570","LAZZARIN LIMA MARTIN IGNACIO":"C00797","LED UNIVERSE SRL":"C00702","LUMMINA SRL":"C00947","MIXDEAL SA":"C00127","PATERNAL SRL":"C00355","STORTONI FRANCO URIEL":"C00758","TWENTY ILUMINACION SRL":"C01006","VIL ELECTRO S.R.L.":"C00804"}},"SEBASTIAN VILLARRUEL":{"clientes":{"ADMA DISTRIBUIDORA S.R.L.":"C02566","ALVAREZ VICTOR ERNESTO":"C00421","ARCE GONZALO MATIAS":"C02671","ARCE GUIDO LUIS":"C01477","BONET MARIA ISABEL":"C02273","CASA BACHETTI S.A.":"C00792","CENTILUZ S.R.L":"C01793","COBLACTRIC S.R.L.":"C01980","COPILAN S.R.L.":"C00496","DISTRIBUIDORA MILER":"C01009","ELECTRICIDAD AREV SRL":"C01226","ELECTRICIDAD AVELLANEDA":"C00048","ELECTRICIDAD BELTRAME SA":"C00623","ELECTRICIDAD CHICLANA SRL":"C01161","ELECTRICIDAD TRIBUNALES S.A.":"C00975","ELECTRO LANUS SRL":"C00607","ELECTRO SERVICE MYE SRL":"C00336","ELECTRO TUCUMAN SA":"C00219","ELECTRO V.D.P. S.A.":"C01964","ELECTROCITY ARGENTINA S A":"C01141","FCG ENERGIA S.R.L":"C01411","IMPORTODOOESTE SRL":"C01213","JOSE RAMON AREAN Y CIA S A":"C01476","KOHEN ILUMINACION S.A.":"C00097","LA FABRICA DE ILUMINACION SRL":"C01989","LUMIGOLD SRL":"C01670","LUZ DESING ILUMINACION S. R. L.":"C02274","MATERIALES ELECTRICOS SA":"C01120","ME INDUSTRIAL":"C01256","ME LIGHTING S.A.":"C01889","MONTIEL PABLO GREGORIO":"C01709","NAVARRO JUAN DOMINGO":"C02226","PANA ILUMINACION SA":"C00916","PROYECTO ELECTRICO SRL":"C00532","RAMIREZ DIAZ NAHUEL":"C00788","SABBAGH EZRA MARTIN":"C00125","TORREVERDE MARKET S.R.L.":"C02625","ZETABURGOS SRL":"C00177"}},"SERGIO SANTORO":{"clientes":{"A1-TEC S.A.":"C02203","ABBA MIX SRL":"C02713","ALGARDATA SISTEMAS INFORMATICOS SOCIEDAD ANONIMA":"C02457","ALVI ELECTRIC SRL":"C00419","AMERICAN CONSULTING GROUP SA":"C02185","BACKNOLOGY S.R.L.":"C02063","BELIO DIEGO PATRICIO":"C02001","BELLUCCI AGUSTIN":"C02661","BESSEL S.R.L.":"C02603","BINAGHI FRANCO":"C02140","BISTECH S.A.":"C02388","BLOK JAVIER HERNAN":"C02074","BOCCHI HERNAN DARIO":"C00302","BRAGHI PABLO OMAR":"C00314","CAMOIA DOMINGO":"C02408","CANEPA CARLOS FERNANDO":"C01327","CARLOS ESTEBAN GRIMOZZI":"C01269","CARLOS JUAN HOSMAN":"C01366","CARRY BIT S.R.L.":"C02067","CELANO MARIA MERCEDES":"C01795","CONTELEC SA":"C01313","DI BENEDETTO ROQUE LUJAN":"C02096","DISTRIBUIDORA BARBIERO SRL":"C00011","DUQUE MARCELO GUSTAVO":"C02545","E CORP SOCIEDAD ANONIMA":"C02615","EBENEGGER DANIEL FERNANDO":"C01731","EL EMPORIO ELECTRICO S.A.":"C00294","ELECTRICIDAD ESCALADA":"C01643","ELECTRICIDAD GRAL. PAZ S.A.":"C01621","ELECTRICIDAD LEON S.R.L.":"C01143","ELECTRICIDAD MITRE":"C00050","ELECTRO INTEGRAL S.A.":"C00248","ELECTRO NAVAL DEL SUR":"C02025","ELECTROINGENIERIA TRENQUE LAUQUEN S.A.":"C00895","EMEGE GROUP S.R.L.":"C01987","EXANET S.A.":"C01389","EXPLOTACIONES PATAGONICAS SOCIEDAD ANONIMA":"C02124","Electricidad Gomez SRL":"C01362","FANESSI GABRIEL DARIO":"C00965","FEDERICO BRUSCANTINI SRL":"C00572","FERNANDEZ HUGO LEONARDO":"C02616","FERNANDEZ JUAN JOSE":"C01764","FERRETERIA MPM":"C02303","FNET SYSTEM S.R.L.":"C02528","FRYDMAN DAMIAN ARMANDO":"C02150","FULL CONTROL SRL":"C02293","GALAN SUSANA LIDIA":"C02219","GARCIA VIRGINIA MARIA":"C01321","GENACER S.R.L.":"C01751","GLOBAL RISK S A":"C02630","GP 9100 S.R.L.":"C02522","GRUPO FADIME SA":"C01329","HERBAS ESPINOZA GABRIEL MATIAS":"C01983","I TEC SOLUCIONES TECNOLOGICAS S.R.L.":"C02296","INTEGRAL ANDINA SRL":"C01953","JPH S.A.":"C02136","KINTRON S.R.L.":"C02142","LEIRAX SRL":"C02046","LUCAS ESTEBAN SCISTRI Y JAQUELINA ESTHER ESCALANTE S. CAP I SECC IV":"C02591","MARCOS S.A":"C01200","MARGARIA DIEGO EDEL":"C00907","MARISCAL ROSA":"C02048","MATCOM S.A":"C02138","MB ELECTRIC SRL":"C01295","MUEBLELUZ S.A.":"C00443","NETIO S R L":"C02262","NEWCOM L.C.S. SA":"C02601","NIELSEN S.R.L.":"C02485","OSHIRO GONZALO HERNAN":"C02196","PABLO MAURICIO FAURE":"C00618","PACHECO PABLO BENJAMIN":"C02202","PACIFICAN GROUP S.A.":"C02166","PETRESKY IGNACIO MARIO":"C00098","PLANETSTORE S.R.L.":"C02086","PLANEX  S A":"C02075","PORSAN SRL":"C01084","POWER SYSTEMS ARGENTINA SA":"C02041","PROPIEDAD PROTEGIDA S.A.S.":"C02197","RADO LILIANA NOEMI":"C02036","ROZZE MARTIN":"C01440","RUBEN SOLITO E HIJOS":"C00995","SA-SEGURIDAD S. R. L.":"C02084","SAAVEDRA EZEQUIEL":"C00180","SALOMON SERGIO DANIEL":"C01480","SAN MIGUEL DANIEL OSCAR":"C02064","SERVINTEL INTERNATIONAL SA":"C02276","SILVA GRISELDA PATRICIA":"C01093","SIMONETTI RENATO":"C02286","SISTEMA INTEGRAL DE SEGURIDAD E INVESTIGACIONES SRL":"C02173","SITELEC S.A.":"C02798","SOCHAN LUIS EDUARDO":"C01728","SORAIRE MIGUEL ALBERTO":"C00136","SUCESIÓN DE ZUBILLAGA NESTOR MARIO":"C01776","TEKNO GROUP ARGENTINA":"C02043","TELETEX SOCIEDAD ANONIMA":"C02112","TRESTERCIO SRL":"C01320","TRIMMER S.A.":"C02327","USS TECNOLOGIA EN SEGURIDAD S.A.":"C02709","VALENALMICH S.A.":"C02468","VEGGETTI FEDERICO":"C02264","VIMELECTRIC S. R. L.":"C01981","WIRED SOLUTIONS":"C02132","XILER SRL":"C02241"}},"SIMON RODRIGUEZ":{"clientes":{"ALPRE S.A.":"C01991","ARDILES CARLOS MANUEL":"C02550","ARMAGALLI S A":"C02531","BATERIAS BURZACO S.A.":"C02472","BENEDETICH GUSTAVO CEFERINO":"C01868","BONORA ELECTRICIDAD":"C00924","BOVALINO CRISTIAN ROQUE":"C00611","BQ TOOLS S.A.":"C01738","CARVAJAL HIDALGO JESSIUSKA DEL CARMEN":"C02515","CASTELLARI ELIO":"C00853","CINCO ALEJANDRO":"C00323","CONTE FABRIZIO NICOLAS":"C02334","CRESPIN PATRICIA EDITH":"C02521","CRISTIAN FERNANDO RIVEROL":"C00810","DAMMIANO ANGEL":"C01403","DAMMIANO-LAREO SH":"C00712","DANIEL ALBERTO COTIGNOLA":"C00913","ELECSA ELECTRICIDAD SA":"C00045","ELECTRICIDAD JUJUY SA":"C01203","ELECTRO BARADERO SS S. CAP I SECC IV":"C02151","ELECTRO MARITIMO SRL":"C01802","ELECTROMAT SRL":"C01871","EMPRESA DE CONSTRUCCION Y SERVICIOS ECOS S A":"C02529","FEROCE GAIDO":"C01839","FIRST LABEL S.R.L.":"C02297","FLORES DANIEL OSCAR":"C02177","GARCIA ALFREDO RICARDO":"C02204","GARRO ELIO AGUSTIN":"C01632","GOMEZ LUISA ESTEFANIA":"C02279","GOMEZ RUBEN DARIO":"C02428","GRUPO BOTRE":"C01705","GRUPO CANFEMA S.R.L":"C02686","GRUPO LANZARD S.R.L.":"C02826","GRUPO LIDER S. A. S.":"C02486","GRUPO O.T SRL":"C02328","GRZECH RUBEN DARIO":"C02239","GUGLIELMINO WALTER MARTIN":"C01501","GULLO MARIA ANTONIA":"C01921","GV SRL":"C01158","HP ELECTRIC SRL":"C00539","ILUMINATE  S. A. S.":"C02014","ISAURRALDE SEBASTIAN MATIAS":"C02605","ISIKAWA SECURITY & BROADCAST SA":"C02255","JACQUARD S.A.S.":"C02200","JB E HIJOS CIA PUBLICITARIA SRL":"C01137","KROMACOLOR PINTURERIAS S.R.L.":"C02659","LUCERO MAXIMILIANO ADRIAN":"C02597","MASCAK EMILIANO":"C02340","MAZADOURIAN LUCAS MAXIMILIANO":"C01758","MIGLIORE S.R.L.":"C02687","MUBARQUI MIGUEL ANGEL":"C01891","MUSMANNO MARCELO ALBERTO":"C01837","NORBERTO FARIAS":"C01291","OBRAS Y SERVICIOS  S R L":"C01577","PABLO ANTONIO MOLISE":"C01249","R&G ELECTRICIDAD S.R.L.":"C02384","REINHOLD Y CIA S R L":"C02517","RIVIECCIO ARIEL EDUARDO":"C01862","RUIZ RAUL EDGARDO":"C01345","SAN ISIDRO LUZ S.R.L.":"C01212","STUMOL SRL":"C00940","SUAREZ JONATHAN ALEJANDRO":"C02705","TOLABA FLORENCIA FLORENTINA":"C02235","TRICARICO FERNANDO JAVIER":"C02650","TRIONFETTI ISABEL DEL CARMEN":"C00341","TROVATO SANDRA ELINA":"C01126","WEB S.A.":"C01935"}},"URIEL NIETO":{"clientes":{}},"WALTER BRAVO":{"clientes":{"AKUAKU S. A. S.":"C02519","ARIAS BARRETO TAMAIBA MARGARITA":"C02551","ASERRADERO PAIMUN S.R.L.":"C02415","BA&DE S.A.S.":"C02785","BAHIA BLANCA SRL":"C02617","BATTAGLIA BAKER NAHUEL DANIEL":"C02498","BERNAT ALFIO HUMBERTO":"C02336","BEROIZ RODOLFO":"C02432","BISSON PABLO ALBERTO":"C02588","BOCHATAY ANDREA VIVIANA":"C02508","BROT SAS":"C02611","BULONERIA LA PLATENSE S. R. L.":"C02397","CASA PALM S A C I I A":"C02653","CHOLILA ANDINA  S.R.L.":"C02446","CHURRI MAQUINARIAS S.R.L.":"C02441","COCCO PABLO NICOLAS":"C02633","COLLADO DARDO FABIO":"C01601","COMERCIAL Y ENERGIA SRL":"C02516","CUSAL S.A.S.":"C02637","D ANTONIO CLAUDIO":"C02383","DA-DI FERRETERIA S A":"C02682","DADAN RUBEN ENRIQUE":"C02473","EL CORRALON SRL":"C02543","EL FUERTE SA":"C02430","EL MARTILLO":"C02721","EL VELERO SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C02634","ELECTROFER FERRETERIAS SR S. A. S.":"C02664","FERRERO DANIEL ANDRES":"C02431","FERRETERIA LA CANTERA SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C02710","FRIDEL GABRIEL HORACIO":"C02345","FRONTONI JOSE LUIS":"C02542","G. Y A. CONSTRUCCIONES Y SERVICIOS S.R.L.":"C02632","GARAGGIOLA ROMINA":"C02491","GARCIA ROUCO Y BOUZA SRL":"C02608","GIORDANO SERGIO MIGUEL":"C02494","GOMEZ CLAUDIA MONICA":"C02678","GOMEZ MARIA DEL CARMEN":"C02403","HOLZMANN MARCOS GERMAN":"C02667","HOMERO Y CIA S.R.L.":"C02619","INDUSTRIAS RIVERA S A":"C02470","IRIZAR CARLOS ALBERTO":"C02420","JUAN CARLOS NARCISI SRL":"C02423","KOLLER ALCIDES YOEL":"C02580","KUNTZ JOSE MARIO":"C02482","LANZETTI JOSE MARIA":"C02587","LEAL FUENTES FRANCISCO JAVIER":"C02511","LEMARCHAND MARCOS MARCELO":"C02442","LOEWEN FAST CORNELIO":"C02502","LUCANERA WALTER DARIO":"C02760","LUIS TEOBALDO MOJANA Y VICTOR MANUEL MOJANA SOC. LEY 19550 CAP I SECC IV":"C02620","MARCONETTO JOSE LUIS":"C02589","MARCOS MARCELA MONICA":"C02393","MARTINA CLAUDIO MIGUEL":"C02590","MARTYNIUK ANDRES JOSE":"C02501","MAS FERRETERIAS S.A":"C02680","MASANTE CELIA MARGARITA":"C02512","MATERIALES Y SERVICIOS SEVILLANO S R L":"C02438","MATRAKAR ANDRES EDUARDO":"C02484","NAMUNCURA SANTIAGO NICOLAS":"C02761","OSES DIEGO HERNAN":"C02614","OTTORINO PAN SOCIEDAD RESPONSABILIDAD LIMITADA":"C02344","PIEDRAS Y MADERAS SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C02436","POTAP CLAUDIO MARCELO":"C02497","PRINCIPI HECTOR ISMAEL":"C02492","QUISPE CARINA LUISA":"C02631","RABE-SEGOVIA S.R.L.":"C02426","REYES MARTA PATRICIA":"C02449","RG YOPPEN S. R. L.":"C02627","SAEZ DANIEL EDUARDO":"C02663","SANCHEZ DANIEL EVARI":"C02604","SEPULVEDA JUAN MANUEL":"C02419","SOLDASUR SOCIEDAD ANONIMA":"C02454","SOLUYA S.R.L.":"C02346","SUMIAGRO CORDOBA S A":"C02474","TODOTALLER NQN S. A. S.":"C02662","TORNERO HORACIO FABIAN":"C02427","TORRES VIDAL CONSTRUCTORA SOCIEDAD DE RESPONSABILIDAD LIMITADA":"C02629","VIAL SERVICIOS SOCIEDAD ANONIMA":"C02628","VIÑAS MAURO JAVIER":"C02582"}},"Z_PRUEBA":{"clientes":{"JULIETA ROMANO":"JULIETA ROMANO","MARKETING":"MARKETING"}}},"tiposAccion":["Bajo Mostrador","Sobre mostrador","Vinilo Interior","Microperforado","Vinilo Exterior","Cartelería","Marquesina","Exhibidor personalizado","Ploteo Exhibidor","Corpóreos","Ploteo Vehicular","Persiana","Banner Gota","Otro"],"marcas":["MACROLED","CHINT","UNIVIEW","DCK","JADEVER","INTECK","WEIDMULLER","RONIN","POWERSWITCH","KING","CORESA"]};

// ─── ENTORNO ──────────────────────────────────────────────────────────────────
const WEBHOOK_TEST_MODE = false;
const WEBHOOK_URL = WEBHOOK_TEST_MODE
  ? 'https://n8n.coresagroup.com/webhook-test/pop-form'
  : 'https://n8n.coresagroup.com/webhook/pop-form';

// ─── ESTADO ───────────────────────────────────────────────────────────────────
let contEspacios = 0;
const editorState = {};
const PIN_R  = 20;
const PIN_FS = 14;
const PIN_MIN_DIST_PCT = 0.07;
const MAX_ESPACIOS = 5;
let pasoActual = 1;
const TOTAL_PASOS = 3;
const INTRO_PASOS = {
  1: 'Indicá el comercial y el cliente para este pedido.',
  2: 'Subí la foto de cada espacio y marcá las acciones POP que necesitás.',
  3: 'Completá la ubicación, quién produce el material y el informe de ventas.'
};

// ─── COMPRESIÓN ───────────────────────────────────────────────────────────────
const IMG_MAX_W      = 800;
const IMG_MAX_W_ORIG = 600;
const IMG_Q_ANNOT    = 0.55;
const IMG_Q_ORIG     = 0.50;

function comprimirImagen(img, maxW, quality) {
  const ratio = img.naturalHeight / img.naturalWidth;
  const w = Math.min(img.naturalWidth, maxW);
  const h = Math.round(w * ratio);
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  c.getContext('2d').drawImage(img, 0, 0, w, h);
  return { canvas: c, dataURL: c.toDataURL('image/jpeg', quality) };
}

// ─── INIT ─────────────────────────────────────────────────────────────────────
function init() {
  // CAMBIO 1: window.DATOS en lugar de DATOS
  if (typeof window.DATOS === 'undefined') {
    console.error('DATOS no está definido — asegurate de que el script de datos carga antes que este.');
    return;
  }
  const sel = document.getElementById('sel-comercial');
  Object.keys(DATOS.comerciales).sort().forEach(c => sel.appendChild(new Option(c, c)));
  sel.appendChild(new Option('Otro (no está en la lista)', '__OTRO__'));
  agregarEspacio();
  actualizarCamposProduccion();
  actualizarWizardUI();
}

// ─── WIZARD POR PASOS ─────────────────────────────────────────────────────────
function irAPaso(n, opts) {
  opts = opts || {};
  n = parseInt(n, 10);
  if (!n || n < 1 || n > TOTAL_PASOS) return;
  if (n === pasoActual) return;

  if (n > pasoActual && !opts.force) {
    for (var i = pasoActual; i < n; i++) {
      if (!validarPaso(i)) return;
    }
  }

  if (pasoActual === 2 && n !== 2) {
    Object.keys(editorState).forEach(function(k) {
      if (editorState[k] && editorState[k].pendingPin) cancelPin(k);
    });
  }

  pasoActual = n;
  actualizarWizardUI();

  if (n === 2) {
    requestAnimationFrame(function() {
      Object.keys(editorState).forEach(function(k) {
        var s = editorState[k];
        if (!s || !s.img) return;
        var canvas = document.getElementById('canvas-' + k);
        if (!canvas) return;
        setCanvasSize(canvas, s.img);
        renderCanvas(k);
      });
    });
  }

  if (!opts.silent) {
    var card = document.querySelector('.page-card');
    if (card) card.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
}

function siguientePaso() {
  if (pasoActual < TOTAL_PASOS) irAPaso(pasoActual + 1);
}

function atrasPaso() {
  if (pasoActual > 1) irAPaso(pasoActual - 1, { force: true });
}

function actualizarWizardUI() {
  document.querySelectorAll('.form-panel').forEach(function(p) {
    p.classList.toggle('is-active', parseInt(p.getAttribute('data-paso'), 10) === pasoActual);
  });

  var intro = document.getElementById('form-intro');
  if (intro) intro.textContent = INTRO_PASOS[pasoActual] || intro.textContent;

  var btnAtras = document.getElementById('btn-atras');
  var btnSig = document.getElementById('btn-siguiente');
  var btnEnviar = document.getElementById('btn-enviar');
  var nota = document.getElementById('nota-aprobacion');
  if (btnAtras) btnAtras.hidden = pasoActual === 1;
  if (btnSig) btnSig.hidden = pasoActual === TOTAL_PASOS;
  if (btnEnviar) btnEnviar.hidden = pasoActual !== TOTAL_PASOS;
  if (nota) nota.hidden = pasoActual !== TOTAL_PASOS;

  actualizarStepper();
}

function actualizarStepper() {
  var step1 = document.getElementById('step-1');
  var step2 = document.getElementById('step-2');
  var step3 = document.getElementById('step-3');
  var line1 = document.getElementById('line-1');
  var line2 = document.getElementById('line-2');
  if (!step1) return;

  [step1, step2, step3].forEach(function(s, idx) {
    s.classList.remove('active', 'done');
    var i = idx + 1;
    if (i < pasoActual) s.classList.add('done');
    if (i === pasoActual) s.classList.add('active');
    s.setAttribute('aria-current', i === pasoActual ? 'step' : 'false');
  });
  if (line1) line1.classList.toggle('step-line-after', pasoActual > 1);
  if (line2) line2.classList.toggle('step-line-after', pasoActual > 2);
}

// ─── LÓGICA COMERCIAL / CLIENTE CON "OTRO" ────────────────────────────────────
function actualizarClientes() {
  const comercial  = document.getElementById('sel-comercial').value;
  const selCom     = document.getElementById('sel-comercial');
  const inputCom   = document.getElementById('input-otro-comercial');
  const btnVolverC = document.getElementById('btn-volver-comercial');
  const selCli     = document.getElementById('sel-cliente');
  const inputCli   = document.getElementById('input-otro-cliente');
  const btnVolverCl = document.getElementById('btn-volver-cliente');

  if (comercial === '__OTRO__') {
    selCom.style.display     = 'none';
    btnVolverC.style.display = 'inline-flex';
    inputCom.style.display   = 'block';
    inputCom.required        = true;
    var lc = document.getElementById('label-comercial');
    if (lc) lc.innerHTML = 'Nombre del comercial <span class="req">*</span>';
    var lcl = document.getElementById('label-cliente');
    if (lcl) lcl.innerHTML = 'Nombre del cliente <span class="req">*</span>';
    setTimeout(() => inputCom.focus(), 0);

    selCli.style.display      = 'none';
    selCli.disabled           = true;
    btnVolverCl.style.display = 'none';
    inputCli.style.display    = 'block';
    inputCli.required         = true;
    inputCli.value            = '';
    actualizarStepper();
    return;
  }

  selCom.style.display     = '';
  btnVolverC.style.display = 'none';
  inputCom.style.display   = 'none';
  inputCom.required        = false;
  inputCom.value           = '';

  selCli.style.display      = '';
  btnVolverCl.style.display = 'none';
  inputCli.style.display    = 'none';
  inputCli.required         = false;
  inputCli.value            = '';

  selCli.innerHTML = '';
  if (!comercial) {
    selCli.innerHTML = '<option value="" disabled selected>Primero elegí un comercial</option>';
    selCli.disabled  = true;
    actualizarStepper();
    return;
  }
  selCli.disabled = false;
  selCli.appendChild(new Option('Seleccioná un cliente...', '', true, true));
  Object.keys(DATOS.comerciales[comercial].clientes).forEach(c => selCli.appendChild(new Option(c, c)));
  selCli.appendChild(new Option('Otro (no está en la lista)', '__OTRO__'));
  actualizarStepper();
}

function volverSelComercial() {
  const selCom     = document.getElementById('sel-comercial');
  const inputCom   = document.getElementById('input-otro-comercial');
  const btnVolverC = document.getElementById('btn-volver-comercial');
  selCom.value             = '';
  selCom.style.display     = '';
  btnVolverC.style.display = 'none';
  inputCom.style.display   = 'none';
  inputCom.required        = false;
  inputCom.value           = '';
  var lc = document.getElementById('label-comercial');
  if (lc) lc.innerHTML = 'Comercial <span class="req">*</span>';
  var lcl = document.getElementById('label-cliente');
  if (lcl) lcl.innerHTML = 'Cliente <span class="req">*</span>';

  const selCli      = document.getElementById('sel-cliente');
  const inputCli    = document.getElementById('input-otro-cliente');
  const btnVolverCl = document.getElementById('btn-volver-cliente');
  selCli.innerHTML          = '<option value="" disabled selected>Primero elegí un comercial</option>';
  selCli.disabled           = true;
  selCli.style.display      = '';
  btnVolverCl.style.display = 'none';
  inputCli.style.display    = 'none';
  inputCli.required         = false;
  inputCli.value            = '';
  actualizarStepper();
}

function onClienteChange() {
  const selCli      = document.getElementById('sel-cliente');
  const inputCli    = document.getElementById('input-otro-cliente');
  const btnVolverCl = document.getElementById('btn-volver-cliente');
  if (selCli.value === '__OTRO__') {
    selCli.style.display      = 'none';
    btnVolverCl.style.display = 'inline-flex';
    inputCli.style.display    = 'block';
    inputCli.required         = true;
    inputCli.value            = '';
    var lcl = document.getElementById('label-cliente');
    if (lcl) lcl.innerHTML = 'Nombre del cliente <span class="req">*</span>';
    setTimeout(() => inputCli.focus(), 0);
  }
  actualizarStepper();
}

function volverSelCliente() {
  const selCli      = document.getElementById('sel-cliente');
  const inputCli    = document.getElementById('input-otro-cliente');
  const btnVolverCl = document.getElementById('btn-volver-cliente');
  selCli.value              = '';
  selCli.style.display      = '';
  btnVolverCl.style.display = 'none';
  inputCli.style.display    = 'none';
  inputCli.required         = false;
  inputCli.value            = '';
  var lcl = document.getElementById('label-cliente');
  if (lcl) lcl.innerHTML = 'Cliente <span class="req">*</span>';
  actualizarStepper();
}

function getComercialFinal() {
  const sel = document.getElementById('sel-comercial');
  if (sel.value === '__OTRO__') {
    return document.getElementById('input-otro-comercial').value.trim();
  }
  return sel.value;
}

function getClienteFinal() {
  const sel = document.getElementById('sel-cliente');
  if (document.getElementById('sel-comercial').value === '__OTRO__') {
    return document.getElementById('input-otro-cliente').value.trim();
  }
  if (sel.value === '__OTRO__') {
    return document.getElementById('input-otro-cliente').value.trim();
  }
  return sel.value;
}

function getCodigoCliente() {
  const com = document.getElementById('sel-comercial').value;
  const cli = document.getElementById('sel-cliente').value;
  if (com === '__OTRO__' || cli === '__OTRO__') return '';
  return (com && cli) ? (DATOS.comerciales[com]?.clientes[cli] || '') : '';
}

// ─── ESPACIO HTML ─────────────────────────────────────────────────────────────
function espacioHTML(n) {
  const btnQ = n > 1
    ? `<button class="btn-remove" onclick="eliminarEspacio(${n})" title="Quitar espacio">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
        </svg></button>` : '';

  return `
  <div class="accion-block" id="espacio-${n}">
    <div class="accion-header">
      <div class="accion-num"><div class="dot">${n}</div> Espacio ${n}</div>
      ${btnQ}
    </div>

    <p style="font-size:13px;color:var(--gray-700);line-height:1.6;margin-bottom:1rem;">
      Fotografiá el espacio donde necesitás el material POP — vidriera, bajomostrador, góndola, etc. Subí la foto y marcá sobre ella cada acción que necesitás.
    </p>

    <div class="field">
      <label class="field-label-row">
        Foto del espacio
        <span class="file-status" id="foto-status-${n}">
          <span class="st-ico">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>
          </span>
          Sin cargar
        </span>
      </label>
      <div class="upload-zone" id="upload-zone-${n}">
        <span class="upload-status" aria-hidden="true">
          <svg class="ico-empty" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>
          <svg class="ico-ok" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6"><polyline points="20 6 9 17 4 12"/></svg>
        </span>
        <div class="upload-copy">
          <p>Subir foto del espacio</p>
          <small>JPG, PNG — hasta 10 MB. Después de cargar, tocá acá de nuevo para cambiarla</small>
          <span class="file-name" id="foto-nombre-${n}"></span>
          <span class="upload-change">Cambiar imagen</span>
        </div>
        <input type="file" id="foto-${n}" accept=".jpg,.jpeg,.png" onchange="onFotoChange(this,${n})">
      </div>

      <div class="img-editor-wrap" id="editor-wrap-${n}">
        <div class="img-editor-toolbar">
          <button class="toolbar-btn active" id="btn-pin-${n}">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
              <circle cx="12" cy="10" r="3"/>
              <path d="M12 21.7C17.3 17 20 13 20 10a8 8 0 1 0-16 0c0 3 2.7 6.9 8 11.7z"/>
            </svg> Marcar acción POP
          </button>
          <div class="toolbar-sep"></div>
          <button class="toolbar-btn danger" onclick="clearPins(${n})">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polyline points="3 6 5 6 21 6"/>
              <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>
              <path d="M10 11v6"/><path d="M14 11v6"/>
            </svg> Limpiar
          </button>
          <span class="toolbar-hint">
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <circle cx="12" cy="12" r="10"/>
              <line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg> Hacé click en la imagen para marcar una acción
          </span>
        </div>

        <div class="img-canvas-container" id="canvas-container-${n}">
          <canvas id="canvas-${n}"></canvas>
          <div class="pin-label-popup" id="pin-popup-${n}">
            <div class="pin-popup-title">
              <span class="pin-num-badge" id="pin-popup-num-${n}">1</span> Nueva acción POP
            </div>
            <div class="pin-popup-field">
              <div class="pin-popup-label-row">
                <label>Tipo de acción <span class="req" style="color:var(--red-500)">*</span></label>
                <button type="button" class="pin-label-help" onclick="abrirGuiaAcciones(event)">
                  <span class="help-tip-q">?</span>
                  <span>¿Qué significa cada acción?</span>
                </button>
              </div>
              <select id="pin-tipo-${n}" onchange="onTipoAccionChange(${n})" style="font-size:13px;padding:7px 8px;min-height:36px;padding-right:28px">
                <option value="" disabled selected>Seleccioná...</option>
                ${DATOS.tiposAccion.map(t => `<option>${t}</option>`).join('')}
              </select>
            </div>
            <div class="pin-popup-field" id="pin-tipo-otro-wrap-${n}" style="display:none">
              <label>Especificá la acción <span class="req" style="color:var(--red-500)">*</span></label>
              <input type="text" id="pin-tipo-otro-${n}" placeholder="Describí el tipo de acción">
            </div>
            <div class="pin-popup-field">
              <label>Marcas <span class="req" style="color:var(--red-500)">*</span></label>
              <div class="ms-field">
                <button type="button" class="ms-trigger empty" id="pin-marca-trigger-${n}" onclick="toggleMarcasPanel(${n}, event)">
                  <span id="pin-marca-label-${n}">Seleccioná una o más...</span>
                </button>
                <div class="ms-panel" id="pin-marca-panel-${n}">
                  ${DATOS.marcas.map(m => `
                    <label class="ms-option">
                      <input type="checkbox" value="${m}" onchange="onMarcaCheck(${n})">
                      ${m}
                    </label>`).join('')}
                </div>
              </div>
            </div>
            <div class="pin-popup-field" id="pin-familias-wrap-${n}">
              <label>Familias / productos <span class="req" style="color:var(--red-500)">*</span></label>
              <input type="text" id="pin-familias-${n}" placeholder="Familias o productos que deben figurar en la gráfica">
            </div>
            <div class="pin-popup-dims" id="pin-dims-wrap-${n}">
              <div class="pin-popup-field">
                <label>Ancho (cm) <span class="req" style="color:var(--red-500)">*</span></label>
                <input type="number" id="pin-ancho-${n}" placeholder="0" min="0" step="0.5">
              </div>
              <div class="pin-popup-field">
                <label>Alto (cm) <span class="req" style="color:var(--red-500)">*</span></label>
                <input type="number" id="pin-alto-${n}" placeholder="0" min="0" step="0.5">
              </div>
            </div>
            <div class="pin-label-popup-footer">
              <button class="btn-cancel-pin" onclick="cancelPin(${n})">Cancelar</button>
              <button class="btn-confirm-pin" onclick="confirmPin(${n})">Confirmar</button>
            </div>
          </div>
        </div>

        <div class="howto-banner">
          <div class="howto-steps">
            <div class="howto-step"><div class="howto-step-num">1</div> Subí la foto</div>
            <div class="howto-step"><div class="howto-step-num">2</div> Hacé click para marcar cada acción POP</div>
            <div class="howto-step"><div class="howto-step-num">3</div> Completá tipo, marcas, familias y medidas</div>
          </div>
        </div>

        <div class="pins-list" id="pins-list-${n}">
          <div class="pins-list-title">Acciones marcadas en este espacio</div>
          <div id="pins-chips-${n}"></div>
        </div>
      </div>
    </div>
  </div>`;
}

// ─── CICLO ESPACIOS ───────────────────────────────────────────────────────────
function agregarEspacio() {
  if (contEspacios >= MAX_ESPACIOS) return;
  contEspacios++;
  const n = contEspacios;
  document.getElementById('acciones-container').insertAdjacentHTML('beforeend', espacioHTML(n));
  editorState[n] = { img: null, pins: [], pinCounter: 0, pendingPin: null, scaleX: 1, scaleY: 1 };

  const canvas = document.getElementById('canvas-' + n);
  canvas.addEventListener('click', function(e) { onCanvasClick(e, n); });

  const container = document.getElementById('canvas-container-' + n);
  const ro = new ResizeObserver(function() {
    const s = editorState[n];
    if (!s || !s.img) return;
    setCanvasSize(canvas, s.img);
    renderCanvas(n);
  });
  ro.observe(container);

  actualizarBotonAgregar();
  actualizarStepper();
}

function eliminarEspacio(n) {
  const el = document.getElementById('espacio-' + n);
  if (el) el.remove();
  delete editorState[n];
  contEspacios--;

  const newState = {};
  document.querySelectorAll('.accion-block').forEach(function(el, i) {
    const old = parseInt(el.id.replace('espacio-', ''));
    const num = i + 1;
    el.id = 'espacio-' + num;
    el.querySelector('.dot').textContent = num;
    el.querySelector('.accion-num').childNodes[1].textContent = ' Espacio ' + num;
    newState[num] = editorState[old] || { img: null, pins: [], pinCounter: 0, pendingPin: null };
  });
  Object.keys(editorState).forEach(k => delete editorState[k]);
  Object.assign(editorState, newState);
  actualizarBotonAgregar();
  actualizarStepper();
}

function actualizarBotonAgregar() {
  document.getElementById('btn-agregar').disabled = contEspacios >= MAX_ESPACIOS;
}

// ─── EDITOR ───────────────────────────────────────────────────────────────────
function setCanvasSize(canvas, img) {
  const containerW = Math.min(canvas.parentElement.clientWidth || 600, 700);
  const ratio = img.naturalHeight / img.naturalWidth;
  canvas.width  = containerW;
  canvas.height = Math.round(containerW * ratio);
  canvas.style.width  = containerW + 'px';
  canvas.style.height = Math.round(containerW * ratio) + 'px';
}

function setUploadLoaded(zone, statusEl, opts) {
  if (!zone) return;
  zone.classList.add('is-loaded');
  zone.style.borderColor = '';
  zone.style.background = '';
  const p = zone.querySelector('p');
  const small = zone.querySelector('small');
  const name = zone.querySelector('.file-name');
  if (p) { p.textContent = opts.title; p.style.cssText = ''; }
  if (small) { small.textContent = opts.subtitle; small.style.cssText = ''; }
  if (name) {
    name.textContent = opts.fileName || '';
    name.style.display = opts.fileName ? 'block' : 'none';
  }
  if (statusEl) {
    statusEl.classList.add('is-loaded');
    statusEl.innerHTML = '<span class="st-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.8"><polyline points="20 6 9 17 4 12"/></svg></span> Cargada';
  }
}

function onFotoChange(input, n) {
  if (!input.files[0]) return;

  const maxBytes = 10 * 1024 * 1024;
  if (input.files[0].size > maxBytes) {
    mostrarModalError('La imagen es demasiado grande (máx. 10 MB). Comprimila antes de subirla.');
    input.value = '';
    return;
  }

  setUploadLoaded(
    document.getElementById('upload-zone-' + n),
    document.getElementById('foto-status-' + n),
    {
      title: 'Imagen cargada',
      subtitle: 'Tocá este recuadro si querés reemplazarla (se borran los pines)',
      fileName: input.files[0].name
    }
  );

  const reader = new FileReader();
  reader.onload = function(e) {
    const img = new Image();
    img.onload = function() {
      const MAX_LOAD_PX = 1200;
      function aplicarImagen(imgFinal) {
        const s = editorState[n];
        s.img = imgFinal;
        s.pins = [];
        s.pinCounter = 0;
        s.pendingPin = null;
        document.getElementById('editor-wrap-' + n).style.display = 'block';
        const canvas = document.getElementById('canvas-' + n);
        setCanvasSize(canvas, imgFinal);
        renderCanvas(n);
        updatePinsList(n);
        actualizarStepper();
      }

      if (img.naturalWidth > MAX_LOAD_PX) {
        const ratio = img.naturalHeight / img.naturalWidth;
        const c = document.createElement('canvas');
        c.width  = MAX_LOAD_PX;
        c.height = Math.round(MAX_LOAD_PX * ratio);
        c.getContext('2d').drawImage(img, 0, 0, c.width, c.height);
        const smallImg = new Image();
        smallImg.onload = function() { aplicarImagen(smallImg); };
        smallImg.src = c.toDataURL('image/jpeg', 0.82);
      } else {
        aplicarImagen(img);
      }
    };
    img.src = e.target.result;
  };
  reader.readAsDataURL(input.files[0]);
}

function renderCanvas(n) {
  const s = editorState[n];
  if (!s || !s.img) return;
  const canvas = document.getElementById('canvas-' + n);
  const ctx = canvas.getContext('2d');
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.drawImage(s.img, 0, 0, canvas.width, canvas.height);
  s.pins.forEach(function(p, i) {
    const px = p.xPct * canvas.width;
    const py = p.yPct * canvas.height;
    drawPin(ctx, px, py, i + 1, p.tipo, p.marca, p.ancho, p.alto, PIN_R, PIN_FS);
  });
}

function drawPin(ctx, x, y, num, tipo, marca, ancho, alto, r, fs) {
  r  = r  || PIN_R;
  fs = fs || PIN_FS;

  ctx.shadowColor = 'rgba(0,0,0,0.35)';
  ctx.shadowBlur = 8;
  ctx.beginPath();
  ctx.arc(x, y, r, 0, Math.PI * 2);
  ctx.fillStyle = '#185FA5';
  ctx.fill();
  ctx.strokeStyle = 'white';
  ctx.lineWidth = 2.5;
  ctx.stroke();
  ctx.shadowBlur = 0;

  ctx.fillStyle = 'white';
  ctx.font = 'bold ' + fs + 'px Manrope,sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(num, x, y);

  const hasTipo  = tipo  && tipo.trim();
  const hasMarca = marca && marca.trim();
  const hasDims  = ancho || alto;
  if (!hasTipo && !hasMarca && !hasDims) return;

  const MAX_MARCA_CHARS = 28;
  const marcaTrunc = hasMarca && marca.length > MAX_MARCA_CHARS
    ? marca.slice(0, MAX_MARCA_CHARS - 1) + '…'
    : marca;

  const dimsText = hasDims ? (ancho || '?') + ' × ' + (alto || '?') + ' cm' : null;

  const fsTipo  = fs * 0.92;
  const fsMarca = fs * 0.78;
  const fsDims  = fs * 0.74;
  const pad    = 8;
  const tagRd  = 5;

  const lines = [];
  if (hasTipo)  lines.push({ text: tipo,       size: fsTipo,  bold: true,  color: '#0C447C' });
  if (hasMarca) lines.push({ text: marcaTrunc, size: fsMarca, bold: false, color: '#378ADD' });
  if (dimsText) lines.push({ text: dimsText,   size: fsDims,  bold: false, color: '#5e646e' });

  const lineGap = 3;
  let totalTextH = 0;
  lines.forEach(function(l, i) {
    totalTextH += l.size * 1.15;
    if (i < lines.length - 1) totalTextH += lineGap;
  });
  const tagH = totalTextH + pad * 1.6;

  let maxW = 0;
  lines.forEach(function(l) {
    ctx.font = (l.bold ? '600' : '500') + ' ' + l.size + 'px Manrope,sans-serif';
    maxW = Math.max(maxW, ctx.measureText(l.text).width);
  });
  const tagW = maxW + pad * 2;

  const canvasW = ctx.canvas.width;
  const canvasH = ctx.canvas.height;
  const margin = 4;

  let tagX = x + r + 6;
  if (tagX + tagW > canvasW - margin) tagX = x - r - 6 - tagW;
  if (tagX < margin) tagX = canvasW - tagW - margin;
  tagX = Math.max(margin, Math.min(tagX, canvasW - tagW - margin));

  let tagY = y - tagH / 2;
  tagY = Math.max(margin, Math.min(tagY, canvasH - tagH - margin));

  ctx.shadowColor = 'rgba(0,0,0,0.12)';
  ctx.shadowBlur = 5;
  ctx.beginPath();
  ctx.moveTo(tagX + tagRd, tagY);
  ctx.lineTo(tagX + tagW - tagRd, tagY);
  ctx.quadraticCurveTo(tagX + tagW, tagY, tagX + tagW, tagY + tagRd);
  ctx.lineTo(tagX + tagW, tagY + tagH - tagRd);
  ctx.quadraticCurveTo(tagX + tagW, tagY + tagH, tagX + tagW - tagRd, tagY + tagH);
  ctx.lineTo(tagX + tagRd, tagY + tagH);
  ctx.quadraticCurveTo(tagX, tagY + tagH, tagX, tagY + tagH - tagRd);
  ctx.lineTo(tagX, tagY + tagRd);
  ctx.quadraticCurveTo(tagX, tagY, tagX + tagRd, tagY);
  ctx.closePath();
  ctx.fillStyle = 'white';
  ctx.fill();
  ctx.strokeStyle = '#185FA5';
  ctx.lineWidth = 1.2;
  ctx.stroke();
  ctx.shadowBlur = 0;

  ctx.save();
  ctx.beginPath();
  ctx.rect(tagX + 2, tagY, tagW - 4, tagH + 1);
  ctx.clip();

  let curY = tagY + pad * 0.8;
  lines.forEach(function(l) {
    ctx.fillStyle = l.color;
    ctx.font = (l.bold ? '600' : '500') + ' ' + l.size + 'px Manrope,sans-serif';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'top';
    ctx.fillText(l.text, tagX + pad, curY);
    curY += l.size * 1.15 + lineGap;
  });
  ctx.restore();
}

// ─── COLISIÓN DE PINS ─────────────────────────────────────────────────────────
function pinColisiona(n, xPct, yPct) {
  const s = editorState[n];
  if (!s) return false;
  const canvas = document.getElementById('canvas-' + n);
  const aspectRatio = canvas ? (canvas.height / canvas.width) : 1;

  for (let i = 0; i < s.pins.length; i++) {
    const p = s.pins[i];
    const dx = (xPct - p.xPct);
    const dy = (yPct - p.yPct) / aspectRatio;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (dist < PIN_MIN_DIST_PCT) return true;
  }
  return false;
}

function getMarcasSeleccionadas(n) {
  return Array.from(document.querySelectorAll('#pin-marca-panel-' + n + ' input[type="checkbox"]:checked'))
    .map(function(cb) { return cb.value; });
}

function cerrarPanelesMarca() {
  document.querySelectorAll('.ms-panel.open').forEach(function(p) { p.classList.remove('open'); });
  document.querySelectorAll('.ms-trigger.open').forEach(function(t) { t.classList.remove('open'); });
}

function toggleMarcasPanel(n, e) {
  if (e) e.stopPropagation();
  const panel = document.getElementById('pin-marca-panel-' + n);
  const trigger = document.getElementById('pin-marca-trigger-' + n);
  const willOpen = !panel.classList.contains('open');
  cerrarPanelesMarca();
  if (willOpen) {
    panel.classList.add('open');
    trigger.classList.add('open');
  }
}

function onMarcaCheck(n) {
  const selected = getMarcasSeleccionadas(n);
  const label = document.getElementById('pin-marca-label-' + n);
  const trigger = document.getElementById('pin-marca-trigger-' + n);
  trigger.classList.remove('error');
  if (selected.length) {
    label.textContent = selected.join(', ');
    trigger.classList.remove('empty');
  } else {
    label.textContent = 'Seleccioná una o más...';
    trigger.classList.add('empty');
  }
}

function onTipoAccionChange(n) {
  const tipo = document.getElementById('pin-tipo-' + n).value;
  const wrap = document.getElementById('pin-tipo-otro-wrap-' + n);
  if (!wrap) return;
  wrap.style.display = tipo === 'Otro' ? 'block' : 'none';
  if (tipo !== 'Otro') {
    const inp = document.getElementById('pin-tipo-otro-' + n);
    if (inp) inp.value = '';
  } else {
    const inp = document.getElementById('pin-tipo-otro-' + n);
    if (inp) inp.focus();
  }
}

function resetPinPopupFields(n) {
  const tipo = document.getElementById('pin-tipo-' + n);
  if (tipo) tipo.value = '';
  document.querySelectorAll('#pin-marca-panel-' + n + ' input[type="checkbox"]').forEach(function(cb) { cb.checked = false; });
  onMarcaCheck(n);
  cerrarPanelesMarca();
  const otro = document.getElementById('pin-tipo-otro-' + n);
  if (otro) otro.value = '';
  const otroWrap = document.getElementById('pin-tipo-otro-wrap-' + n);
  if (otroWrap) otroWrap.style.display = 'none';
  const fam = document.getElementById('pin-familias-' + n);
  if (fam) { fam.value = ''; fam.style.borderColor = ''; }
  document.getElementById('pin-ancho-' + n).value = '';
  document.getElementById('pin-alto-' + n).value = '';
  ['pin-tipo-', 'pin-ancho-', 'pin-alto-', 'pin-tipo-otro-', 'pin-familias-'].forEach(function(id) {
    const el = document.getElementById(id + n);
    if (el) el.style.borderColor = '';
  });
  const trigger = document.getElementById('pin-marca-trigger-' + n);
  if (trigger) trigger.classList.remove('error');
}

function abrirGuiaAcciones(e) {
  if (e) { e.preventDefault(); e.stopPropagation(); }
  const overlay = document.getElementById('modal-guia-acciones');
  if (!overlay) return;
  overlay.hidden = false;
}

function cerrarGuiaAcciones() {
  const overlay = document.getElementById('modal-guia-acciones');
  if (overlay) overlay.hidden = true;
}

function onGuiaImgError() {
  const img = document.getElementById('guia-acciones-img');
  const ph = document.getElementById('guia-placeholder');
  if (img) img.style.display = 'none';
  if (ph) ph.hidden = false;
}

function onCanvasClick(e, n) {
  const s = editorState[n];
  if (!s || !s.img || s.pendingPin) return;

  const canvas = document.getElementById('canvas-' + n);
  const rect   = canvas.getBoundingClientRect();

  const scaleX = canvas.width  / rect.width;
  const scaleY = canvas.height / rect.height;
  const cx = (e.clientX - rect.left) * scaleX;
  const cy = (e.clientY - rect.top)  * scaleY;

  const xPct = cx / canvas.width;
  const yPct = cy / canvas.height;

  if (pinColisiona(n, xPct, yPct)) {
    mostrarToastWarning('Ese lugar está muy cerca de otro pin. Hacé click en una zona libre.');
    return;
  }

  const popup    = document.getElementById('pin-popup-' + n);
  const contRect = document.getElementById('canvas-container-' + n).getBoundingClientRect();
  const pH = 420, pW = 280;

  let pl = e.clientX - contRect.left + 16;
  let pt = e.clientY - contRect.top  + 16;

  if (pl + pW > contRect.width - 4) pl = e.clientX - contRect.left - pW - 16;
  if (pl < 4) pl = 4;

  const canvasVisH = rect.height;
  const clickRelY  = e.clientY - rect.top;
  if (clickRelY + pH + 16 > canvasVisH) pt = e.clientY - contRect.top - pH - 16;
  if (pt < 4) pt = 4;

  popup.style.left = pl + 'px';
  popup.style.top  = pt + 'px';
  popup.style.display = 'block';

  resetPinPopupFields(n);
  const badge = document.getElementById('pin-popup-num-' + n);
  if (badge) badge.textContent = s.pins.length + 1;
  document.getElementById('pin-tipo-' + n).focus();

  s.pendingPin = { xPct, yPct };

  renderCanvas(n);
  const ctx = canvas.getContext('2d');
  drawPin(ctx, xPct * canvas.width, yPct * canvas.height, s.pins.length + 1, '', '', null, null, PIN_R, PIN_FS);

  ['pin-tipo-', 'pin-ancho-', 'pin-alto-', 'pin-familias-', 'pin-tipo-otro-'].forEach(function(id) {
    const el = document.getElementById(id + n);
    if (el) {
      el.onkeydown = function(ev) {
        if (ev.key === 'Enter')  confirmPin(n);
        if (ev.key === 'Escape') cancelPin(n);
      };
    }
  });
}

function confirmPin(n) {
  const s = editorState[n];
  if (!s.pendingPin) return;

  const tipoSel = document.getElementById('pin-tipo-' + n).value.trim();
  const tipoOtro = (document.getElementById('pin-tipo-otro-' + n) || {}).value;
  const tipo = tipoSel === 'Otro' ? (tipoOtro || '').trim() : tipoSel;
  const marcas = getMarcasSeleccionadas(n);
  const marca = marcas.join(' / ');
  const familias = (document.getElementById('pin-familias-' + n).value || '').trim();
  const ancho = document.getElementById('pin-ancho-' + n).value.trim();
  const alto  = document.getElementById('pin-alto-'  + n).value.trim();

  let pinOk = true;
  ['pin-tipo-', 'pin-ancho-', 'pin-alto-', 'pin-familias-', 'pin-tipo-otro-'].forEach(function(id) {
    const el = document.getElementById(id + n);
    if (el) el.style.borderColor = '';
  });
  const trigger = document.getElementById('pin-marca-trigger-' + n);
  if (trigger) trigger.classList.remove('error');

  if (!tipoSel) {
    document.getElementById('pin-tipo-' + n).style.borderColor = 'var(--red-500)';
    pinOk = false;
  }
  if (tipoSel === 'Otro' && !tipo) {
    document.getElementById('pin-tipo-otro-' + n).style.borderColor = 'var(--red-500)';
    pinOk = false;
  }
  if (!marcas.length) {
    if (trigger) trigger.classList.add('error');
    pinOk = false;
  }
  if (marcas.length && !familias) {
    document.getElementById('pin-familias-' + n).style.borderColor = 'var(--red-500)';
    pinOk = false;
  }
  if (!ancho) { document.getElementById('pin-ancho-' + n).style.borderColor = 'var(--red-500)'; pinOk = false; }
  if (!alto)  { document.getElementById('pin-alto-'  + n).style.borderColor = 'var(--red-500)'; pinOk = false; }
  if (!pinOk) return;

  s.pinCounter++;
  s.pins.push({
    xPct:  s.pendingPin.xPct,
    yPct:  s.pendingPin.yPct,
    tipo, marca, familias, ancho, alto,
    id:    s.pinCounter,
  });
  s.pendingPin = null;
  cerrarPanelesMarca();
  document.getElementById('pin-popup-' + n).style.display = 'none';
  renderCanvas(n);
  updatePinsList(n);
  actualizarStepper();
}

function cancelPin(n) {
  editorState[n].pendingPin = null;
  cerrarPanelesMarca();
  document.getElementById('pin-popup-' + n).style.display = 'none';
  renderCanvas(n);
}

function clearPins(n) {
  const s = editorState[n];
  s.pins = []; s.pinCounter = 0; s.pendingPin = null;
  document.getElementById('pin-popup-' + n).style.display = 'none';
  renderCanvas(n);
  updatePinsList(n);
  actualizarStepper();
}

function removePin(n, id) {
  editorState[n].pins = editorState[n].pins.filter(p => p.id !== id);
  renderCanvas(n);
  updatePinsList(n);
  actualizarStepper();
}

function updatePinsList(n) {
  const s     = editorState[n];
  const wrap  = document.getElementById('pins-list-'  + n);
  const chips = document.getElementById('pins-chips-' + n);
  wrap.style.display = s.pins.length ? 'block' : 'none';
  chips.innerHTML = s.pins.map(function(p, i) {
    const dims = (p.ancho || p.alto) ? (p.ancho || '?') + ' × ' + (p.alto || '?') + ' cm' : '';
    return '<span class="pin-chip">'
      + '<span class="pin-chip-dot">' + (i + 1) + '</span>'
      + '<span class="pin-chip-info">'
      + '<span class="pin-chip-tipo">' + p.tipo + '</span>'
      + '<span class="pin-chip-marca">' + p.marca + '</span>'
      + (p.familias ? '<span class="pin-chip-dims">' + p.familias + '</span>' : '')
      + (dims ? '<span class="pin-chip-dims">' + dims + '</span>' : '')
      + '</span>'
      + '<span class="pin-chip-remove" onclick="removePin(' + n + ',' + p.id + ')">×</span>'
      + '</span>';
  }).join('');
}

// ─── IMAGEN ANOTADA (con pins) ────────────────────────────────────────────────
function getAnnotatedImage(n) {
  const s = editorState[n];
  if (!s || !s.img) return null;
  const displayCanvas = document.getElementById('canvas-' + n);
  if (!displayCanvas) return null;

  const srcW  = s.img.naturalWidth;
  const srcH  = s.img.naturalHeight;
  const expW  = Math.min(srcW, IMG_MAX_W);
  const expH  = Math.round(expW * (srcH / srcW));

  const exp = document.createElement('canvas');
  exp.width  = expW;
  exp.height = expH;
  const ctx = exp.getContext('2d');
  ctx.drawImage(s.img, 0, 0, expW, expH);

  const expR  = Math.round(PIN_R  * (expW / displayCanvas.width));
  const expFs = Math.round(PIN_FS * (expW / displayCanvas.width));

  s.pins.forEach(function(p, i) {
    drawPin(ctx, p.xPct * expW, p.yPct * expH, i + 1, p.tipo, p.marca, p.ancho, p.alto, expR, expFs);
  });

  return exp.toDataURL('image/jpeg', IMG_Q_ANNOT);
}

// ─── FORMULARIO ───────────────────────────────────────────────────────────────
function mostrarNombre(input, targetId) {
  const span = document.getElementById(targetId);
  if (input.files[0]) { span.textContent = input.files[0].name; span.style.display = 'block'; }
}

function selectToggle(el) {
  el.closest('.toggle-group').querySelectorAll('.toggle-opt').forEach(o => o.classList.remove('active'));
  el.classList.add('active');
  document.getElementById('produccion').value = el.textContent.trim();
  actualizarCamposProduccion();
}

function esProveedorCoresa() {
  return document.getElementById('produccion').value === 'Proveedor CORESA';
}

function actualizarCamposProduccion() {
  const coresa = esProveedorCoresa();
  const wrapContacto = document.getElementById('wrap-contacto-colocacion');
  const inputContacto = document.getElementById('contacto-colocacion');
  if (wrapContacto) wrapContacto.hidden = !coresa;
  if (!coresa && inputContacto) {
    inputContacto.value = '';
    const field = inputContacto.closest('.field');
    if (field) field.classList.remove('field-error');
  }
}

function marcarError(id, msg) {
  const el = document.getElementById(id);
  if (!el) return;
  const field = el.closest('.field');
  if (!field) return;
  field.classList.add('field-error');
  let errEl = field.querySelector('.field-error-msg');
  if (!errEl) {
    errEl = document.createElement('span');
    errEl.className = 'field-error-msg';
    field.appendChild(errEl);
  }
  errEl.textContent = msg;
  el.addEventListener('change', () => field.classList.remove('field-error'), { once: true });
  el.addEventListener('input',  () => field.classList.remove('field-error'), { once: true });
}

function limpiarErrores() {
  document.querySelectorAll('.field-error').forEach(f => f.classList.remove('field-error'));
  document.querySelectorAll('.upload-error-msg').forEach(m => m.remove());
  document.querySelectorAll('.upload-zone').forEach(function(z) {
    if (z.classList.contains('is-loaded')) return;
    z.style.borderColor = ''; z.style.background = '';
  });
}

function recogerErroresPaso(paso) {
  let ok = true, primer = null;

  if (paso === 1) {
    const com    = document.getElementById('sel-comercial').value;
    const cli    = document.getElementById('sel-cliente').value;
    const comFin = getComercialFinal();
    const cliFin = getClienteFinal();

    if (!com) {
      marcarError('sel-comercial', 'Seleccioná un comercial');
      ok = false; primer = primer || 'sel-comercial';
    } else if (com === '__OTRO__' && !comFin) {
      const inp = document.getElementById('input-otro-comercial');
      inp.style.borderColor = 'var(--red-500)';
      inp.addEventListener('input', () => inp.style.borderColor = '', { once: true });
      ok = false; primer = primer || 'input-otro-comercial';
    }

    if (!cli && com !== '__OTRO__') {
      marcarError('sel-cliente', 'Seleccioná un cliente');
      ok = false; primer = primer || 'sel-cliente';
    } else if ((cli === '__OTRO__' || com === '__OTRO__') && !cliFin) {
      const inp = document.getElementById('input-otro-cliente');
      inp.style.borderColor = 'var(--red-500)';
      inp.addEventListener('input', () => inp.style.borderColor = '', { once: true });
      ok = false; primer = primer || 'input-otro-cliente';
    }
  }

  if (paso === 2) {
    document.querySelectorAll('.accion-block').forEach(function(_, i) {
      const n = i + 1;
      const foto = document.getElementById('foto-' + n);
      const zone = document.getElementById('upload-zone-' + n);
      const s    = editorState[n];

      if (foto && !foto.files.length && zone) {
        zone.style.borderColor = 'var(--red-500)';
        zone.style.background  = '#FFF5F5';
        var fotoErr = zone.nextElementSibling;
        if (!fotoErr || !fotoErr.classList.contains('upload-error-msg')) {
          var msg = document.createElement('span');
          msg.className = 'upload-error-msg';
          msg.textContent = 'La foto del espacio es obligatoria';
          zone.parentNode.insertBefore(msg, zone.nextSibling);
          foto.addEventListener('change', function() {
            zone.style.borderColor = ''; zone.style.background = '';
            var m = zone.nextElementSibling;
            if (m && m.classList.contains('upload-error-msg')) m.remove();
          }, { once: true });
        }
        ok = false; primer = primer || ('upload-zone-' + n);

      } else if (s && s.img && s.pins.length === 0) {
        const editorWrap = document.getElementById('editor-wrap-' + n);
        if (editorWrap) {
          editorWrap.style.outline = '2px solid var(--red-500)';
          editorWrap.style.borderRadius = 'var(--radius-md)';
          let pinErrMsg = document.getElementById('pin-err-' + n);
          if (!pinErrMsg) {
            pinErrMsg = document.createElement('span');
            pinErrMsg.id = 'pin-err-' + n;
            pinErrMsg.style.cssText = 'font-size:11px;color:var(--red-500);font-weight:500;margin-top:6px;display:block;';
            pinErrMsg.textContent = 'Marcá al menos una acción POP en la foto (hacé click sobre la imagen)';
            editorWrap.parentNode.insertBefore(pinErrMsg, editorWrap.nextSibling);
          }
          editorWrap.addEventListener('click', function removePinErr() {
            editorWrap.style.outline = '';
            const m = document.getElementById('pin-err-' + n);
            if (m) m.remove();
            editorWrap.removeEventListener('click', removePinErr);
          }, { once: true });
        }
        ok = false; primer = primer || ('editor-wrap-' + n);
      }
    });
  }

  if (paso === 3) {
    if (!document.getElementById('ubicacion').value.trim()) {
      marcarError('ubicacion', 'Ingresá la dirección del punto de venta');
      ok = false; primer = primer || 'ubicacion';
    }

    if (esProveedorCoresa() && !document.getElementById('contacto-colocacion').value.trim()) {
      marcarError('contacto-colocacion', 'Ingresá un contacto para coordinar la colocación');
      ok = false; primer = primer || 'contacto-colocacion';
    }

    const inputInforme = document.querySelector('#zone-informe input[type="file"]');
    if (inputInforme && !inputInforme.files.length) {
      const zone = document.getElementById('zone-informe');
      zone.style.borderColor = 'var(--red-500)';
      zone.style.background  = '#FFF5F5';
      var infErr = zone.nextElementSibling;
      if (!infErr || !infErr.classList.contains('upload-error-msg')) {
        var msg = document.createElement('span');
        msg.className = 'upload-error-msg';
        msg.textContent = 'El informe de ventas es obligatorio';
        zone.parentNode.insertBefore(msg, zone.nextSibling);
        inputInforme.addEventListener('change', function() {
          zone.style.borderColor = ''; zone.style.background = '';
          var m = zone.nextElementSibling;
          if (m && m.classList.contains('upload-error-msg')) m.remove();
        }, { once: true });
      }
      ok = false; primer = primer || 'zone-informe';
    }
  }

  return { ok: ok, primer: primer };
}

function validarPaso(paso) {
  limpiarErrores();
  const r = recogerErroresPaso(paso);
  if (!r.ok) {
    const el = document.getElementById(r.primer);
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    mostrarToastWarning('Completá los campos obligatorios marcados en rojo');
  }
  return r.ok;
}

function validar() {
  for (var i = 1; i <= TOTAL_PASOS; i++) {
    limpiarErrores();
    var r = recogerErroresPaso(i);
    if (!r.ok) {
      if (i !== pasoActual) irAPaso(i, { force: true, silent: true });
      var el = document.getElementById(r.primer);
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
      mostrarToastWarning('Completá los campos obligatorios marcados en rojo');
      return false;
    }
  }
  return true;
}

function base64ToBlob(base64, mimeType) {
  var byteString = atob(base64.split(',')[1]);
  var ab = new ArrayBuffer(byteString.length);
  var ia = new Uint8Array(ab);
  for (var i = 0; i < byteString.length; i++) ia[i] = byteString.charCodeAt(i);
  return new Blob([ab], { type: mimeType });
}

// ─── SUBIR IMAGEN A DRIVE VÍA N8N ────────────────────────────────────────────
const WEBHOOK_UPLOAD_URL = 'https://n8n.coresagroup.com/webhook/img-pop';

function subirImagenADrive(blob, nombre) {
  var fd = new FormData();
  fd.append('file', blob, nombre);
  return fetch(WEBHOOK_UPLOAD_URL, { method: 'POST', body: fd })
    .then(function(res) {
      if (!res.ok) throw new Error('Upload HTTP ' + res.status);
      return res.json();
    })
    .then(function(data) { return data.url || ''; });
}

// Subir en paralelo de a 2 tareas por vez
function subirEnParalelo(tareas, concurrencia) {
  var urls = {};
  var idx = 0;
  var subidas = 0;
  var total = tareas.length;

  function siguiente() {
    if (idx >= total) return Promise.resolve();
    var i = idx++;
    var tarea = tareas[i];
    return subirImagenADrive(tarea.blob, tarea.nombre)
      .then(function(url) {
        urls[tarea.key] = url;
        subidas++;
        mostrarModalCargando(subidas, total);
        return siguiente();
      });
  }

  var workers = [];
  for (var w = 0; w < Math.min(concurrencia, total); w++) {
    workers.push(siguiente());
  }
  return Promise.all(workers).then(function() { return urls; });
}

function enviarFormulario() {
  if (!validar()) return;

  var btnEnviar = document.getElementById('btn-enviar');
  if (btnEnviar) { btnEnviar.disabled = true; }

  var fecha       = new Date().toLocaleDateString('es-AR', { day: '2-digit', month: '2-digit', year: 'numeric' });
  var comercial   = getComercialFinal();
  var cliente     = getClienteFinal();
  var codCliente  = getCodigoCliente();
  var ubicacion   = document.getElementById('ubicacion').value;
  var produccion  = document.getElementById('produccion').value;
  var contactoColocacion = esProveedorCoresa()
    ? document.getElementById('contacto-colocacion').value.trim()
    : '';
  var comentarios = document.getElementById('comentarios').value;

  var filas = [];
  document.querySelectorAll('.accion-block').forEach(function(_, i) {
    var n = i + 1;
    var s = editorState[n];
    if (!s) return;
    s.pins.forEach(function(p) {
      filas.push({ espacioIdx: n, tipo: p.tipo, marca: p.marca, familias: p.familias || '', ancho: p.ancho, alto: p.alto });
    });
    if (s.pins.length === 0) {
      filas.push({ espacioIdx: n, tipo: '', marca: '', familias: '', ancho: '', alto: '' });
    }
  });

  var espaciosUnicos = [];
  var espaciosSeen = {};
  filas.forEach(function(f) {
    if (!espaciosSeen[f.espacioIdx]) {
      espaciosSeen[f.espacioIdx] = true;
      espaciosUnicos.push(f.espacioIdx);
    }
  });

  var tareas = [];
  espaciosUnicos.forEach(function(idx) {
    var b64annot = getAnnotatedImage(idx);
    if (b64annot) {
      var blobAnnot = base64ToBlob(b64annot, 'image/jpeg');
      tareas.push({ blob: blobAnnot, nombre: 'espacio_' + idx + '.jpg', key: 'url_espacio_' + idx });
    }
    var s = editorState[idx];
    if (s && s.img) {
      var b64orig = comprimirImagen(s.img, IMG_MAX_W_ORIG, IMG_Q_ORIG).dataURL;
      var blobOrig = base64ToBlob(b64orig, 'image/jpeg');
      tareas.push({ blob: blobOrig, nombre: 'original_' + idx + '.jpg', key: 'url_original_' + idx });
    }
  });

  if (_informeBlob) {
    tareas.push({ blob: _informeBlob, nombre: _informeNombre || 'informe.jpg', key: 'url_informe' });
  }

  mostrarModalCargando(0, tareas.length);

  subirEnParalelo(tareas, 2)
    .then(function(urls) {
      var formData = new FormData();
      formData.append('fecha',        fecha);
      formData.append('comercial',    comercial);
      formData.append('cliente',      cliente);
      formData.append('codCliente',   codCliente);
      formData.append('ubicacion',    ubicacion);
      formData.append('produccion',   produccion);
      formData.append('contactoColocacion', contactoColocacion);
      formData.append('comentarios',  comentarios);
      formData.append('filas',        JSON.stringify(filas));
      formData.append('imagenesUrls', JSON.stringify(urls));
      formData.append('adjuntarImagenes', 'true');
      formData.append('cantidadEspacios', String(espaciosUnicos.length));
      tareas.forEach(function(tarea) {
        formData.append(tarea.key.replace(/^url_/, ''), tarea.blob, tarea.nombre);
      });
      return fetch(WEBHOOK_URL, { method: 'POST', body: formData });
    })
    .then(function(res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      // Status 200: éxito directo, sin leer el body para evitar errores de parseo
      mostrarModalExito();
      limpiarFormularioSilencioso();
    })
    .catch(function(err) {
      mostrarModalError('No se pudo enviar. Revisa tu conexión e intentá nuevamente. Detalle: ' + err.message);
    })
    .finally(function() {
      if (btnEnviar) { btnEnviar.disabled = false; }
    });
}

function limpiarFormularioSilencioso() {
  limpiarErrores();
  document.getElementById('sel-comercial').value = '';
  const inputCom = document.getElementById('input-otro-comercial');
  if (inputCom) { inputCom.style.display = 'none'; inputCom.value = ''; }
  document.getElementById('sel-cliente').innerHTML = '<option value="" disabled selected>Primero elegí un comercial</option>';
  document.getElementById('sel-cliente').disabled = true;
  const wrapCli = document.getElementById('wrap-sel-cliente');
  if (wrapCli) wrapCli.style.display = 'block';
  const inputCli = document.getElementById('input-otro-cliente');
  if (inputCli) { inputCli.style.display = 'none'; inputCli.value = ''; }
  document.getElementById('acciones-container').innerHTML = '';
  Object.keys(editorState).forEach(k => delete editorState[k]);
  contEspacios = 0;
  agregarEspacio();
  document.getElementById('ubicacion').value = '';
  document.getElementById('produccion').value = 'Proveedor CORESA';
  document.querySelectorAll('.toggle-opt').forEach((o, i) => o.classList.toggle('active', i === 0));
  const contacto = document.getElementById('contacto-colocacion');
  if (contacto) contacto.value = '';
  actualizarCamposProduccion();
  document.getElementById('comentarios').value = '';
  resetZonaInforme();
  _informeBlob = null;
  _informeNombre = null;
  pasoActual = 1;
  actualizarWizardUI();
}

function limpiarFormulario() {
  if (!confirm('¿Querés limpiar todo el formulario?')) return;
  limpiarFormularioSilencioso();
}

function resetZonaInforme() {
  const zone = document.getElementById('zone-informe');
  if (!zone) return;
  zone.classList.remove('is-loaded');
  zone.innerHTML = `
    <span class="upload-status" aria-hidden="true">
      <svg class="ico-empty" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>
      <svg class="ico-ok" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6"><polyline points="20 6 9 17 4 12"/></svg>
    </span>
    <div class="upload-copy">
      <p>Subir captura del informe</p>
      <small>JPG o PNG — captura de pantalla. Después de cargar, tocá acá de nuevo para cambiarla</small>
      <span class="file-name" id="nombre-informe"></span>
      <span class="upload-change">Cambiar imagen</span>
    </div>
    <input type="file" accept=".jpg,.jpeg,.png" onchange="onInformeChange(this)">
  `;
  zone.style.borderColor = '';
  zone.style.background = '';
  const status = document.getElementById('status-informe');
  if (status) {
    status.classList.remove('is-loaded');
    status.innerHTML = '<span class="st-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg></span> Sin cargar';
  }
}

// ─── INFORME CHANGE ────────────────────────────────────────────────────────────
var _informeBlob = null;
var _informeNombre = null;

function onInformeChange(input) {
  if (!input.files[0]) return;

  const maxBytes = 10 * 1024 * 1024;
  if (input.files[0].size > maxBytes) {
    mostrarModalError('La imagen es demasiado grande (max. 10 MB).');
    input.value = '';
    return;
  }

  const zone = document.getElementById('zone-informe');
  if (!zone) return;

  const reader = new FileReader();
  reader.onload = function(e) {
    const img = new Image();
    img.onload = function() {
      const resultado = comprimirImagen(img, 800, 0.50);
      resultado.canvas.toBlob(function(blob) {
        _informeBlob   = blob;
        _informeNombre = input.files[0].name.replace(/\.[^.]+$/, '') + '.jpg';
      }, 'image/jpeg', 0.50);
    };
    img.src = e.target.result;
  };
  reader.readAsDataURL(input.files[0]);

  setUploadLoaded(
    zone,
    document.getElementById('status-informe'),
    {
      title: 'Captura cargada',
      subtitle: 'Tocá este recuadro si querés reemplazarla',
      fileName: input.files[0].name
    }
  );
}

// ─── MODAL UNIFICADO ─────────────────────────────────────────────────────────
// Un solo modal que transiciona entre: cargando → enviando → éxito / error

function getOrCreateOverlay() {
  var overlay = document.getElementById('modal-overlay');
  if (!overlay) {
    overlay = document.createElement('div');
    overlay.id = 'modal-overlay';
    overlay.style.cssText = 'display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,0.55);backdrop-filter:blur(3px);align-items:center;justify-content:center;padding:1rem';
    document.body.appendChild(overlay);
    // Keyframe spin
    if (!document.getElementById('pop-spin-style')) {
      var st = document.createElement('style');
      st.id = 'pop-spin-style';
      st.textContent = '@keyframes pop-spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}} @keyframes popIn{from{transform:scale(0.88);opacity:0}to{transform:scale(1);opacity:1}}';
      document.head.appendChild(st);
    }
  }
  return overlay;
}

function mostrarModalCargando(subidas, total) {
  var overlay = getOrCreateOverlay();
  var pct = total > 0 ? Math.round((subidas / total) * 100) : 0;
  var msg = subidas === 0
    ? 'Preparando envío...'
    : subidas < total
      ? 'Subiendo imágenes (' + subidas + ' de ' + total + ')...'
      : 'Enviando solicitud...';

  if (overlay.style.display !== 'flex') {
    // Primera vez: construir el modal
    overlay.innerHTML = `
      <div class="modal-box" id="pop-modal-box" style="animation:popIn 0.25s cubic-bezier(0.34,1.56,0.64,1)">
        <div class="modal-icon-wrap" id="pop-modal-icon" style="background:var(--blue-600)">
          <svg id="pop-modal-spinner" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8" style="animation:pop-spin 1.1s linear infinite">
            <path d="M21 12a9 9 0 1 1-6.219-8.56"/>
          </svg>
        </div>
        <h2 class="modal-title" id="pop-modal-title">Enviando solicitud</h2>
        <p class="modal-body" id="pop-modal-msg">${msg}</p>
        <div style="background:var(--gray-200);border-radius:99px;height:6px;width:100%;overflow:hidden;margin-bottom:1.75rem">
          <div id="pop-modal-bar" style="height:100%;background:var(--blue-600);border-radius:99px;width:${pct}%;transition:width 0.35s ease"></div>
        </div>
      </div>`;
    overlay.style.display = 'flex';
  } else {
    // Actualizar estado
    var msgEl = document.getElementById('pop-modal-msg');
    var bar   = document.getElementById('pop-modal-bar');
    if (msgEl) msgEl.textContent = msg;
    if (bar)   bar.style.width = pct + '%';
  }
}

function mostrarModalExito() {
  var overlay = getOrCreateOverlay();
  overlay.innerHTML = `
    <div class="modal-box modal-success" style="animation:popIn 0.25s cubic-bezier(0.34,1.56,0.64,1)">
      <div class="modal-icon-wrap success">
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5">
          <polyline points="20 6 9 17 4 12"/>
        </svg>
      </div>
      <h2 class="modal-title">¡Solicitud enviada!</h2>
      <p class="modal-body">Tu pedido de material POP fue recibido correctamente. El equipo de CORESA lo va a revisar y se pondrá en contacto.</p>
      <button class="modal-btn-ok" onclick="cerrarModal()">Aceptar</button>
    </div>
  `;
  overlay.style.display = 'flex';
  setTimeout(function() { var btn = overlay.querySelector('.modal-btn-ok'); if (btn) btn.focus(); }, 50);
}

function mostrarModalError(msg) {
  var overlay = getOrCreateOverlay();
  overlay.innerHTML = `
    <div class="modal-box modal-error" style="animation:popIn 0.25s cubic-bezier(0.34,1.56,0.64,1)">
      <div class="modal-icon-wrap error">
        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5">
          <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
        </svg>
      </div>
      <h2 class="modal-title">Algo salió mal</h2>
      <p class="modal-body">${msg.replace(/\n/g, '<br>')}</p>
      <button class="modal-btn-ok error" onclick="cerrarModal()">Cerrar</button>
    </div>
  `;
  overlay.style.display = 'flex';
  setTimeout(function() { var btn = overlay.querySelector('.modal-btn-ok'); if (btn) btn.focus(); }, 50);
}

function cerrarModal() {
  var overlay = document.getElementById('modal-overlay');
  if (overlay) overlay.style.display = 'none';
}

document.addEventListener('click', function(e) {
  if (!e.target.closest('.ms-field')) cerrarPanelesMarca();
});

document.addEventListener('keydown', function(e) {
  if (e.key === 'Escape') {
    var overlay = document.getElementById('modal-overlay');
    // Solo cerrar si no está en estado cargando (no tiene spinner activo)
    if (overlay && !document.getElementById('pop-modal-spinner')) cerrarModal();
    var guia = document.getElementById('modal-guia-acciones');
    if (guia && !guia.hidden) cerrarGuiaAcciones();
    cerrarPanelesMarca();
  }
});

function mostrarToastWarning(msg) {
  var el = document.getElementById('toast');
  if (!el) return;
  el.textContent = msg;
  el.style.display = 'block';
  clearTimeout(el._timeout);
  el._timeout = setTimeout(function() { el.style.display = 'none'; }, 3500);
}

function toast(msg) { mostrarToastWarning(msg); }

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}

